### ISSUE TITLE
Bug in rule “headers.mailing-list”: [No mailing list found]

### ISSUE THREAD

**Issue by svgeesus** [w3c/specberus#1003]
This bug used to exist, was fixed, and seems to have broken again. The link to GitHub is not recognized.

 I think this is because the checker assumes `one repo per spec` and CSSWG has one repo for all specs and uses GitHub labels.

And it sees this

```
<dt>Issue Tracking:
     <dd><a href="#issues-index">Inline In Spec</a>
     <dd><a href="https://github.com/w3c/csswg-drafts/labels/css-highlight-api-1">GitHub Issues</a>
```

Mind you there is also this, which seems to be the expected form

```
<p><a href="https://github.com/w3c/csswg-drafts/issues">GitHub Issues</a> are preferred for discussion of this specification.
    When filing an issue, please put the text “css-highlight-api” in the title,
    preferably like this:
    “[css-highlight-api] <i data-lt>…summary of comment…</i>”.
```

Found [while checking `https://www.w3.org/TR/2020/WD-css-highlight-api-1-20201022/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2020%2FWD-css-highlight-api-1-20201022%2F&profile=FPWD&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004).

**Comment by tabatkins** [comment]
Ah, last month they switched from looking for these things in the SotD section (where we have a generic /issues/ url) to looking in the header-dl (where we have the more specific /labels/ url).

Fixed in #1004
