### ISSUE TITLE
Relaxing stability paragraph

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#1005]
@fantasai noticed that the stability paragraph is a bit too strict. At the moment, pubrules requires the stability paragrah to **start** with "Publication as ... does not imply endorsement by the W3C Membership.".

Because of that strict requirement, paragraphs like the following, don't pass pubrules:

> This document was published by the CSS Working Group as a Candidate Recommendation Draft. Publication as a Candidate Recommendation does not imply endorsement by the W3C Membership. A Candidate Recommendation Draft integrates changes from the previous Candidate Recommendation that the Working Group intends to include in a subsequent Candidate Recommendation Snapshot. 

@plehegar ok if we allow other text before the require sentences?

/cc @jennyliang220

**Comment by plehegar** [comment]
yes, it is ok.
