### ISSUE TITLE
[CR] Integrating "Snapshot" and "Draft" in specification subtitle

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#1006]
Request from @fantasai:
```
<fantasai> while we're on the topic, I think it would be nice to fold the "Draft" and "Snapshot" words that are currently in a special <h2> into the main status text
<fantasai> that would streamline things I think, and be less awkward as an HTML structure
<fantasai> do you think that's possible sometime?
<denis> yes, that's actually one option we considered while working on the mockups. We didn't want to make distinctions between the types of CRs but that's doable
<denis> Draft and Snapshot are actually in a <h3>
<fantasai> sorry, that's what I meant
<fantasai> so it would be <h2>W3C Candidate Recommendation Draft, [date]<h2>
<fantasai> <h2>W3C Candidate Recommendation Snapshot, [date]</h2>
<fantasai> rather than having yet another heading for the sub-status
<fantasai> That would look a lot cleaner, and probably read better on screenreaders, too
```

@plehegar I remember we discussed that possibility while working on the mockups. That change will require a bit of work from respec, bikeshed and pubrules but it is doable. WDYT?

**Comment by fantasai** [comment]
FWIW
```
<@vivien> 08:28 <fantasai> so it would be <h2>W3C Candidate Recommendation Draft, [date]<h2>
<@vivien> 08:29 <fantasai> <h2>W3C Candidate Recommendation Snapshot, [date]</h2>
<@vivien> 08:29 <fantasai> rather than having yet another heading for the sub-status
<@vivien> +1
```

Bikeshed fixes are easy, it's just removing a bunch of code, mainly.

**Comment by plehegar** [comment]
No objection from me.

**Comment by jennyliang220** [comment]
After removing `<h3>Draft</h3>`, and use `Candidate Recommendation Draft` in `<h2>`
the longStatus should still be **Candidate Recommendation**:

https://www.w3.org/TR/2020/CRD-css-grid-2-20201021/

**Comment by deniak** [comment]
> After removing `<h3>Draft</h3>`, and use `Candidate Recommendation Draft` in `<h2>`
> the config.longStatus should still be **Candidate Recommendation**, with config.crType **Draft**
> 
> E.g. In this doc, https://www.w3.org/TR/2020/CRD-css-grid-2-20201021/ :
> 
> > This document was published by the CSS Working Group as a **Candidate Recommendation Draft** (longStatus + crType).
> 
> > Publication as a **Candidate Recommendation** (longStatus) does not imply endorsement by the W3C Membership.....

Yes, the SOTD shouldn't change from what we have today. Only the `<h2>` and `<h3>` should be updated.
