### ISSUE TITLE
Specberus seems slower than before.

### ISSUE THREAD

**Issue by jennyliang220** [w3c/specberus#1009]
When [checking document](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2016%2FWD-html51-20160412%2F&profile=WD&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=), it takes a long time before starting (to see the progress bar), and longer time to finish.

Possible reasons:
- Migration from whacko to JSDOM.
- Adding API check when extracting metadata

**Comment by deniak** [comment]
Restarting the process seems to do the trick.
