### ISSUE TITLE
Make sure IG deliverables are not on REC-track

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#1015]
The documents produced by IG cannot be on REC-track.

**Comment by jennyliang220** [comment]
type of document | url | is REC-track
----|----|----
IG-Note | https://www.w3.org/TR/2020/NOTE-vocab-owl-time-agg-20200707/ | false
WG (by IG) | https://www.w3.org/TR/2019/WD-mini-app-white-paper-20190912/ | false

**Comment by jennyliang220** [comment]
I thought about adding check in pp.js, but is's not the best solution.

### Current code
none-REC-track sentence (shown blow in code as `noRec`) are currently checked in pp.js for WG. Adding `if` for IG could be possible. When delivered by IG, the **none-REC-track sentence** must appear.
https://github.com/w3c/specberus/blob/ff960f99900accf1e4110e49fe5e08c3187bf5da/lib/rules/sotd/pp.js#L22-L27

### drawback for WG (by IG)
But this way, if WG doesn't have the **none-REC-track sentence**, the only error pubrules shows would be **Required patent policy paragraph not found.**. Another information will also shown indication the right sentence, but it could be too long to identify it's **none-REC-track sentence** that breaks the rule.

### impossible for IG-Notes
IG-Notes aren't TR documents, thus they don't have patent-policy paragraph and pp.js is not include in the rules.

### Suggestion
Adding a separate rule for **none-REC-track sentence** seems a good idea. But for WG (by IG), we still need to make sure it's in the same sentence with patent policy.

**Comment by jennyliang220** [comment]
IG-Note is sure not on rec-track, so only WG (by IG) need be be checked. Still update pp.js now
