### ISSUE TITLE
Allow GitHub issues' link for label in document rules

### ISSUE THREAD

**Issue by jennyliang220** [w3c/specberus#1032]
Currently Specberus rule says: 

> It must include a public archived place to send comments to. (GitHub repository issue links are expected to be of the form `https://github.com/<USER_OR_ORG>/<REPO_NAME>/issues[/…]`.)

But the code also allows `labels`, so the document should add `labels`.
https://github.com/w3c/specberus/blob/ff960f99900accf1e4110e49fe5e08c3187bf5da/lib/rules/headers/mailing-list.js#L33

BTW, should we also allow 'milestones' like https://github.com/w3c/csswg-drafts/milestone/8 ? 
as well as projects: https://github.com/w3c/csswg-drafts/projects/13 ?

**Comment by deniak** [comment]
+1 to update the document.

Regarding your suggestions, I wouldn't allow milestones and projects as they are expected to terminate at some point.
