### ISSUE TITLE
Choose a code style for specberus

### ISSUE THREAD

**Issue by jennyliang220** [w3c/specberus#1058]
A code style as well as corresponding checker is needed for Specberus.

**Comment by nschonni** [comment]
This has a small comparison of some of the styles that are part of the ESLint init setup https://medium.com/better-programming/comparing-the-top-three-style-guides-and-setting-them-up-with-eslint-98ea0d2fc5b7

**Comment by jennyliang220** [comment]
### Popularity if ESLint and JSHint
(screenshot from https://www.npmtrends.com/eslint-vs-jshint)
![Screen Shot 2021-02-04 at 12 38 55 PM](https://user-images.githubusercontent.com/8498677/106845527-1376dc00-66e6-11eb-9630-b5f2672f647c.png)

### Reasons to choose ESLint
 (from [this article](https://medium.com/@sheldonled/from-jshint-to-eslint-8a0a135fa2bf)):
- JSHint rules are a bit confusing. Some of them do something if true (enforcing) and others do something if false (relaxing)
- ESLint has way more built in rules
- Some ESLint rules are more flexible and configurable
- ESLint makes it possible to write your own rules
- ESLint has more support for JSX and ES6 (we’d need these at some point)
- ESLint has a clearer error messaging, showing which rule is causing the error

---

### Which code style for ESLint to choose: 
google, airbnb or standard (from [this article](https://medium.com/better-programming/comparing-the-top-three-style-guides-and-setting-them-up-with-eslint-98ea0d2fc5b7)):
![](https://miro.medium.com/max/700/1*K51eiJl-y9IfnWFK4IcHCQ.png)

### Important Virtual difference:
Rule|Google | AirBnb| Standard
----|----|----|----
Space before function parentheses|this.setState({error: textStatus}); // no spaces|this.setState({ error: textStatus }); // spaces|this.setState({ error: textStatus }) // No opinion spaces
JSDoc|Required | option | option
Trailing Commas |<p>let topics = [{<br>&nbsp;&nbsp;&nbsp;&nbsp;id,<br>&nbsp;&nbsp;&nbsp;&nbsp;title,<br>}]; // required</p>|<p>let topics = [{<br>&nbsp;&nbsp;id,<br>&nbsp;&nbsp;title,<br>}]; // required</p>|<p>let topics = [{<br>&nbsp;&nbsp;id,<br>&nbsp;&nbsp;title<br>}]; // No</p>

### Popularity:
https://www.npmtrends.com/eslint-config-airbnb-vs-eslint-config-google-vs-standard
![Screen Shot 2021-02-04 at 12 33 42 PM](https://user-images.githubusercontent.com/8498677/106845139-3a80de00-66e5-11eb-92e9-8f3396f51ce8.png)

### Conclusion
Eslint with airbnb wins.
Personally I like airbnb code style, there are more spaces(easier to read), not required JSDOC and restricted Trailing Commas.

The rule https://eslint.org/docs/rules/comma-dangle is diff-friendly:
![Screen Shot 2021-02-04 at 12 43 07 PM](https://user-images.githubusercontent.com/8498677/106845748-8b450680-66e6-11eb-9638-a6eee8661e0d.png)

**Comment by deniak** [comment]
@jennyliang220 sounds good. Let's go with your proposal!

**Comment by jennyliang220** [comment]
Resolved by https://github.com/w3c/specberus/pull/1115
