### ISSUE TITLE
Extract metadata for publication

### ISSUE THREAD

**Issue by astorije** [w3c/specberus#106]
Here are the needed pieces of data:

* **TR status** (WD implied for V1; refuse FPWD and LCWD)
* **Date** (metadata checker: Check that pub date is "today"; problem with TZ: everybody must use ET)
* **Title**
* **Process Rules** (2014 process by default)
* **This version**
* **Latest version**
* **Previous versions** (first one, multiple ones?)
* **Deliverers** (multiple deliverers, not for v1; metadata checker: check that data from Specberus and from registration match)
* **Editors** (ID or username? **Done: ID**)

**Comment by astorije** [comment]
@tripu, as far as I could see, Specberus doesn't send the editor's draft URL. Could you add it please? Thanks!

**Comment by deniak** [comment]
@astorije @tripu The current pubrules doesn't check anything regarding the editor's draft. The easiest would be to add a rule "just" for the extraction but we are starting to mix different things imho.

**Comment by astorije** [comment]
@deniak, agreed. Do you have an idea on how we could avoid this?
I am personally thinking of a sub-library only here for extraction and both Specberus and Echidna rely on it. Since that I have little experience with Specberus, I would not be surprised to be wrong :) In addition, this sounds like the current pubrules checker architecture, proven to be difficult to maintain over time (but probably for other reasons).
The other issue I see is that it's a much bigger feature and in that case your easy route would do the job meanwhile.

**Comment by tripu** [comment]
Having two separate projects/libraries (one for metadata extraction, another one for proper validation) vs. having Specberus doing both was a design decision that we discussed during F2F. And IIRC, we opted for extending Specberus with data extraction, because the way the document would be traversed (and regex'es applied) would be pretty similar in both cases, but at the same time refactoring that in a separate library would be too much work.

So for the time being, I'll add the editor's draft to the list of metadata being returned (if it's feasible). Would that be OK?

**Comment by astorije** [comment]
Perfectly okay by me, @tripu.

**Comment by tripu** [comment]
@astorije: if you approve and merge #127, shall we close this issue?

Maybe move the remaining pieces of (secondary) metadata to a new issue, with label `v1.5` or `enhancement`&hellip;?

**Comment by astorije** [comment]
I think some other issues might arise and it will be best to discuss about them here, in my opinion. So I would vote for leaving this thread open and, whenever I have a question on the subject, I'll post here.

**Comment by tripu** [comment]
Mmmh&hellip; OK, @astorije. I don't like leaving issues open just for that. But no big deal.

**Comment by tripu** [comment]
(Did I mention already that I don't like leaving this open, past its milestone, and containing so many `v1.5`, `enhancement` or `is-this-needed` requests&hellip;? O:-)

**Comment by astorije** [comment]
This can be closed IMO.

**Comment by tripu** [comment]
Done. See issue #143.
