### ISSUE TITLE
Check assets from documents are successfully installed too.

### ISSUE THREAD

**Issue by jennyliang220** [w3c/specberus#1075]
images, svg, stylesheets, scripts...

**Comment by deniak** [comment]
One way to check that is to rely on the linkchecker but there's no easy way to integrate it with specberus.
The other way would be to grab all the internal links and make sure there return a 200.

**Comment by jennyliang220** [comment]
https://phantomjs.org/network-monitoring.html could be an option to see Network resources. And we need to check links
