### ISSUE TITLE
Bug in rule “headers.dl”: Unable to state that there is no preliminary implementation report

### ISSUE THREAD

**Issue by svgeesus** [w3c/specberus#1080]
For A CR with no preliminary implementation report, it does not seem possible to persuade the checker that no report exists.

```
No implementation report link found.
Document identifier information must be presented in a dl list, where each dt element marks up 
an identifier role ("This Version", "Latest Version", "Previous Version", etc.) 
and each dd element includes a link whose link text is the identifier.
```

I tried an Implementation Report dl in the headers, with "none" or "(None)", but get a complaint that these are not links.

I tried a simple `<p>There is no preliminary implementation report.</p>` which _used_ to work, but no longer does.

Found [while checking `https://www.w3.org/TR/2020/CR-css-box-3-20201222/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2020%2FCR-css-box-3-20201222%2F&profile=CR&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2020).

By the way, the reason is that CSS Box 3 is a restatement of the box model section of CSS 2.1; the explanatory text is updated but there are no new features. So this was already tested for CSS 1, CSS 2, and CSS 2.1. This spec just gives us a module to link to, rather than CSS 2.1, for definitions related to the box module.

**Comment by jennyliang220** [comment]
In [pubrules rules](https://www.w3.org/pubrules/doc/rules/?profile=CR#implReport) there is:

>  It must include a link to a preliminary interoperability or implementation report, or a statement that no such report exists.

But currently pubrules don't check a paragraph `<p>There is no preliminary implementation report.</p>` as a statement, @plehegar shall we specify the wording and upgrade feature for implementation report?

**Comment by svgeesus** [comment]
> currently pubrules don't check a paragraph <p>There is no preliminary implementation report.</p> as a statement,

It used to, because I have put similar statements into specifications in the past (because the checker was complaining), and then it was satisfied.

**Comment by jennyliang220** [comment]
`There is no preliminary implementation report.` would be the sentence in the document. Add this to the rule and document
