### ISSUE TITLE
Specberus freezes

### ISSUE THREAD

**Issue by svgeesus** [w3c/specberus#1081]
While attempting to check [this publication](https://www.w3.org/TR/2020/CR-webaudio-20201222/)

The page starts to load, no results are returned and the page freezes (I left it for 30 minutes, no change).

I was able to check other specifications with no issue, seems specific to this one.

**Comment by deniak** [comment]
Pubrules seems to have a hard time dealing with large documents. We'll investigate but in the meantime, we restarted the process and I'm able to get the report.

**Comment by svgeesus** [comment]
Thanks, I will have another go, but unless it is all good to go right now, I suspect this large document is going to have to wait until January.

**Comment by svgeesus** [comment]
I wasn't able to get pubrules checker to work on this document in December, but trying again in mid January it was able to run to completion in a reasonable time (and I did about 12 runs to get the document pubrules happy). So this problem appears to be resolved.
