### ISSUE TITLE
Bug in rule “headers.mailing-list”: [WHAT]

### ISSUE THREAD

**Issue by skynavga** [w3c/specberus#1145]
[EXPLANATION]

Rule does not recognize mailing list links employed by TTML2 (see attached image).

<img width="1150" alt="Screen Shot 2021-02-28 at 3 21 26 PM" src="https://user-images.githubusercontent.com/377455/109433990-badeea00-79d8-11eb-97da-b8eb6841845e.png">

HTML fragment not recognized reads is as follows (from SoTD):

<pre>
Comments about this document are welcome by filing an &lt;a href="https://github.com/w3c/ttml2/issues">issue on GitHub&lt;/a> or
sending email to &lt;a href="mailto:public-tt@w3.org">public-tt@w3.org&lt;/a>
(&lt;a href="mailto:public-tt-request@w3.org?subject=subscribe">subscribe&lt;/a>,
&lt;a href="http://lists.w3.org/Archives/Public/public-tt/">archives&lt;/a>)
with a subject line starting with &lt;code>[ttml2]&lt;/code>.
</pre>

Found [while checking `https://raw.githack.com/w3c/ttml2/issue-1220-cr2-publishing-package-build/index.html`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fraw.githack.com%2Fw3c%2Fttml2%2Fissue-1220-cr2-publishing-package-build%2Findex.html&profile=CR&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2020).

**Comment by deniak** [comment]
Hi @skynavga , The error description is actually incomplete. We now require the link to be in the headers of the document. In the case of ttml2, it should probably be under the section "Participate:". We'll update the error description to avoid confusion.
