### ISSUE TITLE
Support h1 with span

### ISSUE THREAD

**Issue by xfq** [w3c/specberus#1146]
The h1 of [clreq](https://w3c.github.io/clreq/) contains a `span`, but it cannot be published because of [the title element and the h1 element are not the same](https://www.w3.org/pubrules/doc/rules/?profile=WD#title). (There is also a `br` in the `h1`, but that is [another issue](https://github.com/w3c/specberus/pull/1044).)

We did not include `span` in `title` because `title` does not support `span` elements. (See [HTML issue](https://github.com/w3c/html/issues/1292).)

The span was added in https://github.com/w3c/clreq/commit/3b8671e166b80f06cd3596d402ab2388ac0340af

Related code in specberus: https://github.com/w3c/specberus/blob/main/lib/rules/headers/h1-title.js

(See also https://github.com/w3c/clreq/issues/72 for background.)

/cc @r12a

/cc @himorin (because [jlreq](https://w3c.github.io/jlreq/) may have the same issue)

**Comment by r12a** [comment]
I thought that Marcos fixed this some time ago so that the h1 and title elements could have different text.  If the span is used only in the h1 and there is a title element also, then it should work, no?

**Comment by jennyliang220** [comment]
@r12a Sadly pubrules is currently not smart enough to ignore `<span>` or other HTML elements:
https://github.com/w3c/specberus/blob/main/lib/rules/headers/h1-title.js#L17-L20

it'll be fixed in #1147
