### ISSUE TITLE
Bug in rule “headers.copyright”:  ignores the license used

### ISSUE THREAD

**Issue by svgeesus** [w3c/specberus#1166]
Checker gives this error

> Missing link 'https://www.w3.org/Consortium/Legal/ipr-notice#Legal_Disclaimer' with text 'liability'.
The copyright must use the following markup (fill in with the appropriate year, years, or year range).

> Copyright © 2021 W3C ® ( MIT , ERCIM , Keio, Beihang). W3C liability, trademark and document use rules apply.
> Include this source code:

```html
<p class="copyright"><a href="https://www.w3.org/Consortium/Legal/ipr-notice#Copyright">
Copyright</a> © 2021 <a href="https://www.w3.org/">
<abbr title="World Wide Web Consortium">W3C</abbr></a><sup>®</sup>
 (<a href="https://www.csail.mit.edu/"><abbr title="Massachusetts 
Institute of Technology">MIT</abbr></a>, <a href="https://www.ercim.eu/">
<abbr title="European Research Consortium for Informatics and 
Mathematics">ERCIM</abbr></a>, <a href="https://www.keio.ac.jp/">Keio</a>, 
<a href="https://ev.buaa.edu.cn/">Beihang</a>). 
W3C <a href="https://www.w3.org/Consortium/Legal/ipr-notice#Legal_Disclaimer">liability</a>, 
<a href="https://www.w3.org/Consortium/Legal/ipr-notice#W3C_Trademarks">trademark</a> and 
<a href="https://www.w3.org/Consortium/Legal/copyright-documents">document use</a> rules apply.</p>
```

While the (Bikeshed-generated)  document actually contains

```html
<p class="copyright" data-fill-with="copyright"><a href="https://www.w3.org/Consortium/Legal/ipr-notice#Copyright">
Copyright</a> © 2021 <a href="https://www.w3.org/">
<abbr title="World Wide Web Consortium">W3C</abbr></a><sup>®</sup>
 (<a href="https://www.csail.mit.edu/"><abbr title="Massachusetts 
Institute of Technology">MIT</abbr></a>, <a href="https://www.ercim.eu/">
<abbr title="European Research Consortium for Informatics and 
Mathematics">ERCIM</abbr></a>, <a href="https://www.keio.ac.jp/">Keio</a>, 
<a href="https://ev.buaa.edu.cn/">Beihang</a>). 
W3C <a href="http://www.w3.org/Consortium/Legal/ipr-notice#Legal_Disclaimer">liability</a>, 
<a href="https://www.w3.org/Consortium/Legal/ipr-notice#W3C_Trademarks">trademark</a> and 
<a href="https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document" 
rel="license">permissive document license</a> rules apply. </p>
```

The difference which the checker sees, is that the disclaimer link uses https instead of http, which is easily fixed.

Raising this issue to report that, had I done as the checker suggested and blindly copy-pasted the *must be used* markup, it would have changed the license from **W3C Software and Document** to **W3C Document**.

Found [while checking `https://www.w3.org/TR/2021/CR-css-scroll-snap-1-20210311/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2021%2FCR-css-scroll-snap-1-20210311%2F&profile=CR&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2020).

**Comment by svgeesus** [comment]
I noticed this again today - while pubruling the Web Audio specification. It didn't like the link I had and insisted it be changed to the one for the document license. So the Proposed Rec was nearly published with the wrong license!

**Comment by svgeesus** [comment]
@plehegar documents accidentally getting published with the wrong license is fairly serious

**Comment by jennyliang220** [comment]
Test cases:

## 1. Payments working group
- charter: https://www.w3.org/Payments/WG/charter-201912.html
- Licensing in charter: This Working Group will use the <a href="https://www.w3.org/Consortium/Legal/copyright-software">W3C Software and Document license</a> for all its deliverables.
- document delivered: https://www.w3.org/TR/2021/CRD-payment-request-20210629/
- current copyright: 
```
...and [permissive document license](https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document) rules apply.
```
- Data from API:
```
"doc-licenses": [{
    "uri": "https://www.w3.org/Consortium/Legal/copyright-software",
    "name": "W3C Software and Document License"
}],
```
- new copyright (every current spec need to change their template):
```
...and [W3C Software and Document License](https://www.w3.org/Consortium/Legal/copyright-software) rules apply.
```
## 2. EOWG
- charter: https://www.w3.org/WAI/EO/charter2020
- Licensing in charter: This Working Group will use the<i> </i><a href="https://www.w3.org/Consortium/Legal/copyright-documents">W3C Document License</a> for some of its deliverables, and for deliverables that are intended to be modified, it will use a more clearly permissive Creative Commons license  (<a href="https://creativecommons.org/licenses/by/4.0/">CC-BY</a>) or the <a href="https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document">W3C Software and Document License</a>.
- document delivered: ??(none on /TR)

## 3. Accessibility Guidelines WG
- charter: https://www.w3.org/2019/12/ag-charter
- Licensing in charter: This Working Group will use the <a href="https://www.w3.org/Consortium/Legal/copyright-documents">W3C Document license</a> for normative deliverables and the <a href="https://www.w3.org/Consortium/Legal/copyright-software">W3C Software and Document license</a> for informative deliverables.
- document delivered: https://w3c.github.io/wcag/guidelines/22/
- current copyright: 
```
... and <a rel="license" href="https://www.w3.org/Consortium/Legal/copyright-documents">document use</a> rules apply.
```
- Data from API:
```
"doc-licenses": [{
    "uri": "https://www.w3.org/Consortium/Legal/copyright-documents",
    "name": "W3C Document License"
},{
    "uri": "https://www.w3.org/Consortium/Legal/copyright-software",
    "name": "W3C Software and Document License"
}],
```
- new copyright (every current spec need to change their template):
@@ TODO?
```
...and [@@ TODO?]() rules apply.
```

**Comment by jennyliang220** [comment]
Hi @deniak @plehegar , as listed [above](https://github.com/w3c/specberus/issues/1166#issuecomment-878426237). Are test case 1 (Payments) and test case 3 (Accessibility Guidelines) both using the wrong copyright? If we stick to the `name` and `uri` given in the API `doc-licenses`, all the documents' copyrights should change their content before getting published next time.

**Comment by plehegar** [comment]
EO doesn't publish in /TR, so we're fine.

Payments seems to be the case that they're using the dated version of the copyright rather than latest, right?

AGWG seems a non-deterministic case, ie we can't check unless we add more info in the API, which seems overkill at the moment. As long as the doc uses on the 2 W3C licenses, we should let them publish.

**Comment by jennyliang220** [comment]
> Payments seems to be the case that they're using the dated version of the copyright rather than latest, right?

The URL points to the same copyright, Pubrules could allow both. But the text is different. **permissive document license** -> **W3C Software and Document License**(text in the charter), @plehegar shall we allow both?
