### ISSUE TITLE
REC-track recognition can be improved.

### ISSUE THREAD

**Issue by jennyliang220** [w3c/specberus#1195]
Currently REC-track.js only recognise the sentence:
> The group does not expect this document to become a W3C Recommendation.

https://github.com/w3c/specberus/blob/d8f0bc99f5b4b6fec91ef5d43f637018b3cef078/lib/rules/metadata/rectrack.js#L11

But there is one more sentence can have the same meaning, e.g. in [webcodecs document](https://www.w3.org/TR/2021/WD-webcodecs-codec-registry-20210408/):

> This document is intended to become a W3C Working Group Note.

**Comment by deniak** [comment]
The bit rec-track should be extracted from the Patent Policy paragraph depending on the presence of the following sentence: `The group does not expect this document to become a W3C Recommendation.`.
No need to look for another sentence
