### ISSUE TITLE
Compound documents: exception requested for CSS test annotations

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#1202]
@frivoal noticed one of the CSS specs was rejected by Echidna because of it relies on 2 external resources (see [echidna report](https://labs.w3.org/echidna/api/status?id=c7532d2c-b705-42e3-a948-845b2e0093e3)):
* https://test.csswg.org/harness/annotate.js
* https://test.csswg.org/harness/stylesheets/annotate.css

Following the discussion, @plinss is requesting that we allow these resources as it wouldn't affect the specifications even if they aren't available.

@plehegar can we add that exception? see [syreq](https://lists.w3.org/Archives/Team/sysreq/2021Apr/0173.html) for more details.

**Comment by svgeesus** [comment]
We have been publishing CSS specifications which link to CSS test annotations **for years**. These exceptions were _already allowed_, so this looks to be a recent bug.

**Comment by deniak** [comment]
@svgeesus the rule wasn't enforced in the past and we did made some changes to check that rule.
Do you have a record of the exception? To be clear, the system is built is such a way that we can add exceptions but there must be a formal approval.

**Comment by frivoal** [comment]
I'm not part of the Team, so I don't have access to records of formal decisions. But while this is investigated, could you consider the fact that many tens (likely hundreds) of publications with this deliberate feature have already happen, with full knowledge of multiple team contacts of the WG in question, as evidence that there's at least enough precedent on this to keep allowing it while we deal with the necessary paperwork to find or get formal approval.

If the formal decision ends up being against (which would very much surprise me, given the above), we can always block it then, and the few additional publications that will have gone through in the meanwhile won't make much of a difference, given the numerous documents on TR that already have this.

Removing this feature from a random (from the point of view of the reader) subset of the CSSWG's publication while we figure this out seems much more harmful.

**Comment by deniak** [comment]
@jennyliang220, can you please add these resources to the allowlist? @frivoal, @svgeesus, please let us know if other resources should also be added.

**Comment by jennyliang220** [comment]
Allow everything under https://test.csswg.org/harness/
