### ISSUE TITLE
Disclosures link

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#1212]
Starting from today, the old IPP link we require (https://www.w3.org/2004/01/pp-impl/{id}/status) redirects to the group IPR tab (https://www.w3.org/groups/wg/{shortname}/ipr), e.g.
https://www.w3.org/2004/01/pp-impl/45211/status  ➡️ https://www.w3.org/groups/wg/webperf/ipr

Pubrules requires the old link in the SotD. Should we allow both until the generators get updated?

/cc @plehegar @wseltzer @vivienlacourba

**Comment by vivienlacourba** [comment]
+1 to temporarily allow for both links.

If this not being worked on already on bikeshed and respec could you create issues on both repos and even submit an PR if that is an easy fix?

Thanks!
