### ISSUE TITLE
Bug: [EXCEPTION] The document could not be parsed, it's neither a TR document nor a Member Submission.

### ISSUE THREAD

**Issue by svgeesus** [w3c/specberus#1234]
The error gives no indication what could be wrong. The document is produced by bikeshed and looks just like all the other TR docs that CSSWG publish.

Found [while checking `https://www.w3.org/TR/2021/WD-web-animations-1-20210513/`](https://www.w3.org/pubrules/?url=https://www.w3.org/TR/2021/WD-web-animations-1-20210513/&profile=auto).

**Comment by svgeesus** [comment]
The editor is unable to auto publish, see https://github.com/w3c/csswg-drafts/issues/6211

Which is why I was trying a manual publish

**Comment by jennyliang220** [comment]
hi @svgeesus , please update your bikeshed version to the latest.

As discussed [here](https://github.com/w3c/specberus/issues/838#issuecomment-821734344), bikeshed Version 2.4.0 has removed `id="subtitle"` for **W3C Working Draft, 13 May 2021**. And Pubrules has made the corresponding change.

The error message from Pubrules could be improved (very soon), as proposed in https://github.com/w3c/specberus/issues/1209.

**Comment by birtles** [comment]
I am unable to publish even with bikeshed 2.4.0.

**Comment by jennyliang220** [comment]
Hi @birtles , that's strange. Does the generated document have `id="subtitle"` in the source code?

The latest bikeshed document has:

```
<meta content="Bikeshed version 5c7bc9381, updated Wed May 12 18:18:08 2021 -0700" name="generator">
```

without `id="subtitle"` for `<h2>`

```
<h2 class="no-num no-toc no-ref heading settled" id="subtitle">
    <span class="content">W3C Working Draft, 
        <time class="dt-updated" datetime="2021-05-13">13 May 2021</time>
    </span>
</h2>
```

**Comment by birtles** [comment]
Hi @jennyliang220!

I am simply changing 'ED' to 'WD' locally and I get:

```
  <meta content="Bikeshed version 94f325bff, updated Tue May 4 07:07:04 2021 -0700" name="generator">
```

and

```
   <h2 class="no-num no-toc no-ref heading settled" id="profile-and-date"><span class="content">W3C Working Draft, <time class="dt-updated" datetime="2021-05-14">14 May 2021</time></span></h2>
```

But when I try to publish I get:

https://labs.w3.org/echidna/api/status?id=56872409-0642-4a7c-bdce-bd46da2f8dae

i.e.

```
The document could not be published: Cannot read property 'message' of undefined
```

**Comment by jennyliang220** [comment]
hi @birtles , thanks for providing the echidna status link.

```
"specberus": {
   "status": "ok",
   "errors": []
},
....
"publish": {
   "status": "error",
   "errors": [
      "TypeError: Cannot read property 'message' of undefined"
   ]
},
```

In the status message, **specberus** return a status ok, which means your document is valid. Echidna, however, is having trouble doing 'publish'. 

https://github.com/w3c/echidna/blob/a7880b3dfe7e0c10040695dfa470173fdab1c9db/lib/publisher.js#L70-L72
```
        switch (response.statusCode) {
          case 501:
            return Promise.reject(new Error(body.message));
```

The server somehow responds with 501 with `body` empty. @deniak any idea?

**Comment by deniak** [comment]
I looked a bit and I couldn't find any logs of the request for the 'publish' job. I suspect a network issue as MIT was doing some maintenance on some of our servers around that time.
@birtles, can you please try to submit the document again?

**Comment by birtles** [comment]
@deniak Hi! I've been seeing this problem since 3 days ago I'm afraid. I just tried again now but got the same result:

https://labs.w3.org/echidna/api/status?id=54938aec-857a-424f-8427-40592dee5155

**Comment by deniak** [comment]
@birtles I now understand the issue. The [previous version](https://www.w3.org/TR/2018/WD-web-animations-1-20181011/) was published by both the SVG and CSS WGs. The new version you are submitting is only published by the CSS WG. There's a limitation in Echidna that prevent that kind of changes so the document first needs to be published by the webmaster and once it's done, you will be able to publish with Echidna. This mainly comes from how we used to handle WG call for exclusions.

That being said, there seems to be a bug in how Echidna handles the errors reported by the backend. I'll take a look at that.

In the meantime, could you send a email to webreq@w3.org so we can publish the document for you? The next publication slot is on May 18.

**Comment by birtles** [comment]
> @birtles I now understand the issue. The [previous version](https://www.w3.org/TR/2018/WD-web-animations-1-20181011/) was published by both the SVG and CSS WGs. The new version you are submitting is only published by the CSS WG. There's a limitation in Echidna that prevent that kind of changes so the document first needs to be published by the webmaster and once it's done, you will be able to publish with Echidna. This mainly comes from how we used to handle WG call for exclusions.

That rings a bell and I suspect that's why this spec has gone for so long without re-publishing.

> That being said, there seems to be a bug in how Echidna handles the errors reported by the backend. I'll take a look at that.

Thank you!

> In the meantime, could you send a email to [webreq@w3.org](mailto:webreq@w3.org) so we can publish the document for you? The next publication slot is on May 18.

Done.

**Comment by svgeesus** [comment]
While the previous discussion cleared up what was wrong with one particular document, the general issue of obscure and unhelpful error message persists.

I just got it again:

Found [while checking `https://www.w3.org/TR/2021/NOTE-audio-eq-cookbook-20210608/`](https://www.w3.org/pubrules/?url=https://www.w3.org/TR/2021/NOTE-audio-eq-cookbook-20210608/&profile=auto).

and here, there is no such joint-publishing issue.

**Comment by svgeesus** [comment]
There is literally no help on what exactly "could not be parsed" or what made it "not a /TR document". This particular oe is a (blank) note that I am trying to get through pubrules before pasting in the actual content.

**Comment by svgeesus** [comment]
In this case the actual error was


```html
<h2>W3C Note, 08 June 2021</h2>
```

which should have been

```html
<h2>W3C Working Group Note, 08 June 2021</h2>
```

**Comment by jennyliang220** [comment]
You are right @svgeesus , this new error message seems to help. Pubrules relies heavily on the `<h2>` to identify the document and check with corresponding rules.
