### ISSUE TITLE
Pubrules is slow...

### ISSUE THREAD

**Issue by jennyliang220** [w3c/specberus#1240]
https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2021%2FWD-webgpu-20210518%2F&profile=FPWD&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2020

Takes really long to start. Don't know what's going on. Need to check, or give a hint on UI

**Comment by deniak** [comment]
@jennyliang220 can you try to run it locally and see if you can reproduce the problem?

**Comment by svgeesus** [comment]
It does seem _super_ slow today. Pubrules checking an (admittedly large) REC is never terminating; and checking a small NOTE was fairly slow.

**Comment by jennyliang220** [comment]
the slow REC url: https://www.w3.org/TR/2021/REC-webaudio-20210610/ (takes forever)

**Comment by deniak** [comment]
Providing more resources to the machines running pubrules seems to help. Given the size of the document and the number of links to check, I get a response after 23sec.
