### ISSUE TITLE
Question about `longStatus` in code.

### ISSUE THREAD

**Issue by jennyliang220** [w3c/specberus#1251]
`sr.config.longStatus` is used in multiple places, to represent **type** of the document. E.g. SOTD section must mention what type of document is this.

https://github.com/w3c/specberus/blob/2d79e706121ef49138927f9212a52ca7522568f2/lib/rules/sotd/status.js#L7-L16

The question is, currently the rule for `longStatus` seems not clear, some FP document mentions "First Public" in "Status of this document", while some don't.

Type of document | status | longStatus | Sotd Paragraph
----|----|----|----
WD| WD |Working Dtaft| This document was published by the @@ Group as a **Working Draft**
FPWD| WD |**First Public** Working Draft| This document was published by the @@ Group as a **First Public Working Draft**
WG-Note|NOTE|Working Group Note|T his document was published by the @@ Group as a **Working Group Note**
FPWG-NOTE| NOTE |Working Group Note (FP?)|This document was published by the @@ Group as a (First Public) **Working Group Note**
IG-NOTE|NOTE|Interest Group Note|This document was published by the @@ Group as an **Interest Group Note**
FPIG-NOTE|NOTE|Interest Group Note(FP?)|This document was published by the @@ Group as a  (First Public)  **Interest Group Note**

@deniak , what do you think? Shall it get unified?

**Comment by deniak** [comment]
We cannot check that without prior discussions with @plehegar and the spec generators maintainers.

**Comment by deniak** [comment]
Closing as we won't change the longStatus
