### ISSUE TITLE
Better error reporting when checking an ED

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#1258]
When pubrules checks an ED, it'll simply report the following error:
`Error: [EXCEPTION] The document could not be parsed, it's neither a TR document nor a Member Submission.` 

This can be confusing and pubrules could report a better error.

**Comment by svgeesus** [comment]
Fixing this would help document editors check their EDs which in turn would give less work for staff contacts to wrangle documents into pubrules compliance, besides resulting in better EDs (at least for the link checking part).
