### ISSUE TITLE
Bug in rule “sotd.publish”: grammar

### ISSUE THREAD

**Issue by svgeesus** [w3c/specberus#1276]
"This document was published by the @@ Working Group as a Recommendation. It includes proposed addition, introducing new features since the Previous Recommendation."

should be (plural **additions**, to be consistent with rest of sentence)

"This document was published by the @@ Working Group as a Recommendation. It includes proposed additions, introducing new features since the Previous Recommendation."

Found [while checking `https://www.w3.org/TR/2021/REC-webaudio-20210610/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2021%2FREC-webaudio-20210610%2F&profile=REC&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2020).

**Comment by jennyliang220** [comment]
Hi @svgeesus , pubrules recognizes both single and plural statements in the check: 

https://github.com/w3c/specberus/blob/d51f26cfeb4d2bc6e69c35da51cea5f2ea34a184/lib/validator.js#L565-L569

The [wording in the document](https://github.com/w3c/specberus/blob/8819a47d4d1f0b620cb24854fabc5f8596786183/lib/rules.json#L1351), however, can be refined. Good catch🍻.
