### ISSUE TITLE
Drop mailing list requirement in header 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/specberus#1308]
Despite the warning from Specberus, seems that few specs (I actually can't find any!) include a mailing list in the header of the document. 

Could we just drop this requirement entirely? 

For ReSpec at least, the mailing list link is included in the SoTD.

**Comment by jennyliang220** [comment]
Hi @marcoscaceres , the need of mailing list is discussed [in issue #775](https://github.com/w3c/specberus/issues/775#issuecomment-701611719) last year.

cc @plehegar .

**Comment by marcoscaceres** [comment]
Oh yes!Thank you for the reminder! although, I think everyone is just ignoring the warning, so it's just noise. It come up in spec-prod, so I'm wondering if we should just consider dropping it. 

The mailing list is still something that gets mentioned in the SoTD, which hopefully is sufficient.

**Comment by marcoscaceres** [comment]
Hi @jennyliang220, spoke to @plehegar about it during our weekly catch. He's ok for us to proceed with removing the warning (see his 👍 above). Do you have any thoughts or concerns in case we overlooked anything?
