### ISSUE TITLE
Bug in rule “headers.dl”: Cannot find any editors for this document

### ISSUE THREAD

**Issue by svgeesus** [w3c/specberus#1311]
The message is

**Cannot find any editors for this document.**
The editors'/authors' names must be listed, with attribute data-editor-id="@@". Affiliations and email addresses are optional; email addresses are not recommended. If an editor/author is acknowledged in an earlier version of this document and the individual's affiliation has since changed, list the individual using the notation "<name>, <affiliation> (until DD Month YYYY)". If the list of authors is very long (e.g., the entire Working Group), identify the authors in the acknowledgments section, linked from the head of the document. Distinguish any contributors from authors in the acknowledgments section.

The markup is

```html
<dl>
        <dt class="editor">Editors:</dt>
        <dd class="editor"  data-editor-id="43052">Vladimir Levantovsky (W3C Invited Experts)</dd>
        <dd class="editor"  data-editor-id="51758">Raph Levien (Google)</dd>
</dl>
```

Found [while checking `https://www.w3.org/TR/2021/REC-WOFF2-20210706/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2021%2FREC-WOFF2-20210706%2F&profile=REC&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2020).

**Comment by jennyliang220** [comment]
Hi @svgeesus , pubrules is currently retrieving data from the first `<dl>`. Please merge the "Editors" with the `<dl>` above in the source code.

A good example for single `<dl>` would be the [css-fonts-5](https://www.w3.org/TR/2021/WD-css-fonts-5-20210629/) we published together several days earlier.

**Comment by svgeesus** [comment]
Thanks @jennyliang220

**Comment by svgeesus** [comment]
It would help if the documentation for this error mentioned this contraint
