### ISSUE TITLE
Bug in rule “sotd.rec-addition”: doesn't contain substantive changes

### ISSUE THREAD

**Issue by svgeesus** [w3c/specberus#1312]
**The error message:**

> This document doesn't contain substantive changes, paragraph &lt;p class="correction">Proposed corrections are marked in the document.&lt;/p> should be removed.
Modifications in W3C Recommendation are divided into "new features" and "changes". Recommendations with modifications must include the following paragraphs depending on the changes.

> For substantive changes, there should be a paragraph with class="correction":

>    Proposed corrections are marked in the document.

> &lt;p class="correction">Proposed corrections are marked in the document.&lt;/p>

> For new features, there should be a paragraph with class="addition":

>    Proposed additions are marked in the document.

> &lt;pclass="addition">Proposed additions are marked in the document.&lt;/p>

**The problem**

the phrase "Proposed corrections" does not appear anywhere in the document, so I can't remove it.

Now, I **used** to have 

```html
<div class="correction"><a href="https://www.w3.org/Consortium/Process/#candidate-correction">Candidate corrections</a> are marked in the document.</div
```

but that is now commented out (in an attempt to pass pubrules)

Found [while checking `https://www.w3.org/TR/2021/REC-WOFF2-20210706/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2021%2FREC-WOFF2-20210706%2F&profile=REC&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2020).

**Comment by svgeesus** [comment]
Suspect this is related to https://github.com/w3c/specberus/pull/1079

**Comment by jennyliang220** [comment]
Hi @svgeesus, the document you mentioned is "Recommendation with candidate changes", which Pubrules does not understand now (it should, so there's a bug). I'll help you with the document, and pubrules' issue is noted here: https://github.com/w3c/specberus/issues/1316
