### ISSUE TITLE
Joint-publication with different version of Patent Policy.

### ISSUE THREAD

**Issue by jennyliang220** [w3c/specberus#1319]
Currently, Pubrules only take the Patent Policy link from **the first WG/IG** (as deliverer) mentioned in the document.
https://github.com/w3c/specberus/blob/3d21736b319d3077b99f60099820d99f2e5c3604/lib/rules/metadata/patent-policy.js#L17-L20

Although it can be really rare, but it could be possible for **groups publishing a spec jointly choose different versions of Patent Policy.** 

@plehegar @wseltzer any opinions?
- Shall we allow this case? (In echidna or manual publication)
- Do groups' PP versions have to be aligned to publish a spec?
- Will it cause any impact on legal stuff?

**Comment by plehegar** [comment]
I'd like to see the use case here. It seems a bug to have 2 Groups working on the same document with 2 different patent policies.

**Comment by jennyliang220** [comment]
> I'd like to see the use case here. It seems a bug to have 2 Groups working on the same document with 2 different patent policies.

There's no current use case. But we neither did we check it, nor prevent it. It's a rare case, I suggest we add a rule to make sure the groups have the same PP version.

One question left, @plehegar if 2 groups use different PP versions, can they still publish using manual publication? Or the groups should align their PP version?

**Comment by deniak** [comment]
> There's no current use case. But we neither did we check it, nor prevent it. It's a rare case, I suggest we add a rule to make sure the groups have the same PP version.

Yes, there shouldn't be any problem if the WGs are operating under the same PP. This is just a security check.

@plehegar, the same kind of comment also applies for the document license check we are working on. We expect the license mentioned in the document matches the one in the charter of each group.

**Comment by wseltzer** [comment]
A given document should be published under only one Patent Policy, to which all participants in contributing groups have agreed. Since we don't often publish joint documents, and change the Patent Policy even less frequently, I don't see a reason to make code more complex to anticipate this corner case.

**Comment by jennyliang220** [comment]
We could simply return an error if the groups use a different PP version. As well as document copyright mentioned in the charter as https://github.com/w3c/specberus/issues/1166 shows.
