### ISSUE TITLE
Embedded SVG in CSS breaks specberus?

### ISSUE THREAD

**Issue by plehegar** [w3c/specberus#1331]
I was looking at:
[[
      "specberus": {
        "status": "failure",
        "errors": [
          {
            "key": "not-same-folder",
            "extra": {
              "base": "http://owl.w3.org//fb1033b4-30e0-4e7e-9fb7-4f087d13eee6/",
              "url": "nullimage/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' version='1.1' height='300px' width='125px'><text x='0' y='100' fill='red' font-size='15' fill-opacity='0.20'>Obsolete</text></svg>"
            },
            "detailMessage": "This resource or link found in document (nullimage/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' version='1.1' height='300px' width='125px'><text x='0' y='100' fill='red' font-size='15' fill-opacity='0.20'>Obsolete</text></svg>) is not in the same folder as the document (http://owl.w3.org//fb1033b4-30e0-4e7e-9fb7-4f087d13eee6/). Please install them in the same folder.",
            "type": {
              "name": "links.linkchecker",
              "section": "compound",
              "rule": "compoundFilesLocation"
            }
          }
        ]
      },
]]
https://labs.w3.org/echidna/api/status?id=fb1033b4-30e0-4e7e-9fb7-4f087d13eee6

and noticed that the SVG is inside the CSS:

view-source:https://w3c.github.io/navigation-timing/ (Line 14)

Is that a specberus limitation?

**Comment by jennyliang220** [comment]
Hi @plehegar , this problem is fixed and deployed on the latest version of Specberus and Echidna.
