### ISSUE TITLE
Is the w3c_process_revision id useless now?

### ISSUE THREAD

**Issue by astorije** [w3c/specberus#134]
In currently published documents, the process statement looks like:

```html
<p>This document is governed by the <a id="w3c_process_revision" href="http://www.w3.org/2014/Process-20140801/">1 August 2014 W3C Process Document</a>.</p>
```

To be confirmed with @ianbjacobs, but if I remember correctly, `id="w3c_process_revision"` was added for the sole goal to help the Pubrules checker find the statement in the document.

With Specberus, this statement is detected by its actual text and link. Do we need to tell editors that they can drop this piece of data now?

**Comment by darobin** [comment]
If you're using a spec tool, it generates this for you. If you're not using a spec tool, you deserve the pain :)

**Comment by astorije** [comment]
What pain? I'm asking if the `id` became useless with Specberus :)

**Comment by darobin** [comment]
I know, but my point is it's getting generated anyway at zero cost to people. I'm not sure we need to change the rules, even if it's to remove something :)

**Comment by astorije** [comment]
It's just pollution... And when I see how difficult it is to convince people that tools need a new piece of metadata from time to time, it's kind of sad if we cannot get rid of useless ones...

**Comment by deniak** [comment]
We rely on that id to extract the process
