### ISSUE TITLE
Take down http://pubrules.nodejitsu.com/

### ISSUE THREAD

**Issue by tripu** [w3c/specberus#136]
Shouldn't we remove (or at least update) [the previous public deployment of the project](http://pubrules.nodejitsu.com/)?

**Comment by deniak** [comment]
@tripu I think so. @darobin, could you add a redirect to http://www.w3.org/2014/10/pubrules/ ?

**Comment by darobin** [comment]
As soon as you have a normal URL to which to redirect to, I will!

**Comment by tripu** [comment]
@darobin, done. The new URL is [`https://labs.w3.org/pubrules/`](https://labs.w3.org/pubrules/). Please redirect there.

RIP nodejitsu.

**Comment by astorije** [comment]
I get the `labs.w3.org` part, but why the `pubrules` one instead of `specberus`? `pubrules` was the old system, don't we want to call a potato a potato for this new one? Unless it's more "accepted" among our members...
Anyway, I was just wondering, curious to see other people's reactions.

**Comment by tripu** [comment]
@astorije, I see reasons for both names. I was going to set up `specberus`; @deniak suggested `pubrules`. You're right in that, for consistency, if we have `https://labs.w3.org/echidna/`, we should have `https://labs.w3.org/specberus/`. But it's also true that folks are used to calling the thing *pubrules*, and that's the name that will come to their heads&hellip;

**Solved**: I enabled both `https://labs.w3.org/pubrules/` and `https://labs.w3.org/specberus/` in labs.w3.org :¬)

**Comment by tripu** [comment]
**Update**: @deniak isn't sure it's good practice enabling both URLs, and it's true we already announced `pubrules`&hellip;

@astorije, let's discuss today and settle on a name.

@darobin, please hold it with the redirect until we've reached consensus here.

**Comment by astorije** [comment]
Agreed, having both URLs for the same tool is confusing and not necessarily a good practice indeed.

@darobin, @dontcallmedom, as editors (step back a bit as if you didn't know the system :-) ), what do you think is best/less confusing?

**Comment by dontcallmedom** [comment]
I prefer https://labs.w3.org/pubrules/ (specberus is a name for our internal cuisine, not a name we need to advertize, not would benefit from advertizing)

**Comment by astorije** [comment]
Fair enough.
Discussion with @tripu and @deniak this morning, we agreed to go with your suggestion indeed.

**Comment by tripu** [comment]
OK. Only `/pubrules` enabled now.
@darobin, please proceed at your earliest convenience :¬)

**Comment by darobin** [comment]
The Nodejitsu deployment has been retired!
