### ISSUE TITLE
[Bug] TAG publication shouldn't check group charter

### ISSUE THREAD

**Issue by jennyliang220** [w3c/specberus#1377]
https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2021%2FNOTE-design-principles-20210923%2F&profile=WG-NOTE&validation=simple-validation&noRecTrack=true&informativeOnly=true&echidnaReady=false&patentPolicy=

#### Error: charter
`The group does not have any current charter, please contact the team contact.`

Pubrules shouldn't check charter for TAG documents.

#### Error: document license
`Could not get the document license from the API. Please make sure this group has a current charter associated with at least one document license.`
The TAG's charter doesn't mention document license. also in #1378

**Comment by deniak** [comment]
duplicate #1481
