### ISSUE TITLE
Copyright and PP check for TAG documents.

### ISSUE THREAD

**Issue by jennyliang220** [w3c/specberus#1378]
The TAG's [charter](https://www.w3.org/2004/10/27-tag-charter.html) is operating PP2004 and it didn't show in "Patent Policy" which document license the TAG is using.

@ylafon @wseltzer any ideas?

**Comment by deniak** [comment]
Duplicate #1481

**Comment by deniak** [comment]
@wseltzer, the TAG and the AB are special groups that can publish to /TR. It seems there is no specific document license attached to these groups. Can you confirm they can use whatever license they want so we can fix the current rule?

**Comment by wseltzer** [comment]
Thanks @deniak. I support removing the pubrules check for a specific license for TAG and AB documents.
