### ISSUE TITLE
PubRules hangs

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/specberus#1383]
Trying: 

https://www.w3.org/pubrules/?url=https%3A%2F%2Fmarcoscaceres.github.io%2Fplayground%2Fgeo.html&profile=CR&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2020

Using:
https://marcoscaceres.github.io/playground/geo.html

**Comment by marcoscaceres** [comment]
Oh wait... now it's back..

**Comment by deniak** [comment]
Since yesterday (11pm UTC), some of our services became slow to respond. This might be related. We are investigating the issue.
