### ISSUE TITLE
New attribute “data-editor-id” won't exist in non-HTML5 specs; accept also <span id="data-editor-id-1234">Foo McBar</span> for older doctypes

### ISSUE THREAD

**Issue by tripu** [w3c/specberus#141]

**Comment by astorije** [comment]
@tripu, what do you mean by "New attribute [...] won't exist in HTML5 specs"?

Regarding older doctypes, I would drop support. I think I remember @plehegar saying at some point that Echidna should only publish HTML5 documents. I think it's only fair...

**Comment by tripu** [comment]
OK, @astorije; if we're OK *not* supporting specs *not* written in HTML5, then we can close this issue. It's just that the first WD @deniak & I picked randomly for tests today happened to be in HTML 4.01, and we thought those should work with Echidna/Specberus too&hellip;

@plehegar?

**Comment by tripu** [comment]
Removing from the `v1` milestone after chatting with the team; only HTML5 documents for the moment. We'll evaluate later the need for older doctypes.

**Comment by deniak** [comment]
After discussing with @plehegar, we'll only accept HTML5 docs starting from Aug 1, 2016
