### ISSUE TITLE
Bug: missing L10n message [WD][front-matter][gitRepo]

### ISSUE THREAD

**Issue by dbaron** [w3c/specberus#1419]
When [checking](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2021%2FWD-css-values-4-20211016%2F&profile=WD&validation=simple-validation&informativeOnly=false&echidnaReady=false&patentPolicy=pp2020) the latest published css-values-4, pubrules says:

> Cannot find the "Feedback" `<dt>` in the headers of the document.
>
> NB: Pubrules hit an internal error while checking this rule. Please file this issue on GitHub to help developers fix the problem (you can submit it as is; no additional information is required).

**Comment by jennyliang220** [comment]
Thank you @dbaron for reporting, will fix soon.
