### ISSUE TITLE
Error messages about w3c-state are confusing.

### ISSUE THREAD

**Issue by dbaron** [w3c/specberus#1421]
The `no-w3c-state` error message currently says:

> Cannot find the <code>&lt;p id="w3c-state"&gt;</code> element for profile and date.<br><br>
Please make sure the <code>&lt;p id="w3c-state"&gt;W3C @@Profile, DD Month Year&lt;/p&gt;</code> element can be selected by <code>document.getElementById("w3c-state")</code>; <br>If you are using bikeshed, please update to the latest version.

If you follow its advice, you instead get the no-w3c-state-link error, which says:

> Cannot find the link of the W3C profile pointing to "https://www.w3.org/standards/types#xx".

This is very confusing.  The second message is saying that *inside* the p suggested by the first error, there needs to be an `a` element pointing to the appropriate section of https://www.w3.org/standards/types .

The first error message should give a correct example instead of an incorrect one, and the second error message should be clearer.

(Also, nobody has actually patched bikeshed yet to do this, though I might do so tomorrow, so the "update to the latest version" advice isn't useful.)

**Comment by svgeesus** [comment]
See https://github.com/tabatkins/bikeshed/issues/2163

**Comment by jennyliang220** [comment]
resolved by https://github.com/w3c/specberus/commit/3c16491c8811b284d3181c49e8cf7a2e3e227fe7
