### ISSUE TITLE
Remove xx-Amended profiles from Pubrules.

### ISSUE THREAD

**Issue by jennyliang220** [w3c/specberus#1430]
Hi @plehegar, can we remove the profiles CR Amended, PR Amended, REC Amended, and REC Rescinded? The new Process allows editors to re-publish an spec, and it's been a long time since someone publish an **amended** spec.

**Comment by plehegar** [comment]
Rescinded should stay.
https://www.w3.org/2021/Process-20211102/#deactivation

 CR Amended, PR Amended, REC Amended can be removed.

**Comment by deniak** [comment]
Amended documents have been removed
