### ISSUE TITLE
Issue with Permission spec

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/specberus#1433]
Hi, I'm having a weird issue publishing the Permission spec... for some reason, Specberus is finding the 2020 Policy, but I'm unsure why. If you see the editor's draft:
https://w3c.github.io/permissions/

The SoTD has: 
> This document was produced by a group operating under the 1 August 2017 W3C Patent Policy. 

Which should match the right `sotd.pp` rule ("wrong-pp-from-charter"). I can't seem to find "20200915" in the generated source?

https://labs.w3.org/echidna/api/status?id=46d8380d-bc1f-470e-b4c7-cd9c749fd488

Any ideas what might be wrong?

**Comment by deniak** [comment]
I found the bug in Echidna. It should now be fixed.
I retriggered the action causing the extra notifications you received. Sorry about that.

**Comment by marcoscaceres** [comment]
Oh no problem! Happy that you found found the issue. Thanks for re-triggering it.
