### ISSUE TITLE
Is the sentence `the document will be updated` mandatory?

### ISSUE THREAD

**Issue by jennyliang220** [w3c/specberus#1435]
> It is expected that the document will be updated from time to time to include new information.

The sentence above appears in **CRY, CRYD, DNOTE, DRY, NOTE, RY, STMT** mockups. @plehegar , is this sentence mandatory for these profiles?

**Comment by plehegar** [comment]
https://w3c.github.io/tr-design/p2021mockup/cryd-6.5.2.html gives the choice between 2 sentences. I don't think we want to enforce the exact sentence. So, I favor pubrules not checking for them.

**Comment by jennyliang220** [comment]
Hi @plehegar , Pubrules is checking "the choice between 2 sentences" now, either sentence would pass the check.

`It is expected that the document will be updated from time to time to include new information.` is from the 2nd paragraph of [SotD of cryd.html](https://w3c.github.io/tr-design/p2021mockup/cryd-6.5.2.html).

**Comment by plehegar** [comment]
I wrote "I favor pubrules not checking for them".  That means that the sentence is not mandatory.
