### ISSUE TITLE
bug in CRD stability check

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/specberus#1449]
Specberus complains on a CRD (e.g. a [recent attempted publication via Echidna](https://lists.w3.org/Archives/Public/public-tr-notifications/2021Dec/0030.html)) about the stability statement, [apparently expecting](https://labs.w3.org/echidna/api/status?id=1a77e454-52d8-4fb0-a96f-2b43bc0401c8) either "This is a draft document and may be updated, replaced or obsoleted by other documents at any time." or "This document is maintained and updated at any time. Some parts of this document are work in progress."

[ReSpec includes](https://github.com/w3c/respec/blob/ffc4b52c4500fa2a12a271ed6366358a5b1fa55c/src/w3c/templates/sotd.js#L131) the additional sentence "It is inappropriate to cite this document as other than work in progress." 

My reading of the [CRD template](https://github.com/w3c/tr-design/blob/27df7538024e8dad611a2b4140635ef3fe24a178/p2021mockup/crd-6.3.8.2.html) and the associated [discussion](https://github.com/w3c/tr-design/issues/205#issue-690737406) is that ReSpec is correct that CRD should have that sentence. (although it looks like ReSpec would also needs to be updated to NOT have it for CRS).

If my reading is correct, the code to fix is at https://github.com/w3c/specberus/blob/b85fa61046c3778ca1f99dfe72349eab3ddf3705/lib/rules/sotd/draft-stability.js#L17 where it should look at CRD vs CR rather than the common `longStatus` "Candidate Recommendation"

**Comment by jennyliang220** [comment]
You're right, @dontcallmedom. Will fix this soon.

**Comment by deniak** [comment]
@dontcallmedom you retriggered the request just before I finish the deployment. Can you retry again now?

**Comment by deniak** [comment]
Ah, never mind. I see it actually went  through.
