### ISSUE TITLE
Bug in rule “sotd.supersedable”: No "status of this document"

### ISSUE THREAD

**Issue by svgeesus** [w3c/specberus#1477]
I get the following error:

> No “status of this document” introduction (eg absent, not using HTTPS, wrong copy).
It must begin with the following boilerplate text:

>    This section describes the status of this document at the time of its publication. A list of current W3C publications can be found in the W3C technical reports index at https://www.w3.org/TR/.

> Include this source code:

```html
<p><em>This section describes the status of this document at the time of its publication. A list of current W3C publications can be found in the <a href="https://www.w3.org/TR/">W3C technical reports index</a> at https://www.w3.org/TR/.</em></p>
```

Which is odd, because I pasted _exactly the above source code_ into the document and it still can't find it.

```html
<h2 class="no-num no-toc no-ref heading settled" id="status"><span class="content">
Status of this document</span></h2>
  <div data-fill-with="status">

    <p><em>This section describes the status of this document at the time of its publication. A list of current W3C publications can be found in the <a href="https://www.w3.org/TR/">W3C technical reports index</a> at https://www.w3.org/TR/.</em></p>

... etc ...
</div>
```
Presumably the checker can deal with the `div`, right? It finds the rest of the sotd, in that same div.

Found [while checking `https://www.w3.org/TR/2021/DNOTE-css-2021-20211214/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2021%2FDNOTE-css-2021-20211214%2F&profile=DNOTE&validation=simple-validation&informativeOnly=false&echidnaReady=false&patentPolicy=pp2020).

**Comment by svgeesus** [comment]
This is blocking publication, can someone take a look?

**Comment by xfq** [comment]
cc @deniak

**Comment by deniak** [comment]
@svgeesus the documentation for the rule was not up-to-date. I've just fixed it and the error should now specify the right markup to use. Sorry for the inconvenience.
@jennyliang220, can you please review all the documentation for the different rules to make sure they are up-to-date?
