### ISSUE TITLE
Bug in rule “sotd.publish”: The homepage https://www.w3.org/groups/wg/css should appear 

### ISSUE THREAD

**Issue by svgeesus** [w3c/specberus#1478]
Looks like the wrong check (the one for a Standards-track document) is being made.

> The homepage https://www.w3.org/groups/wg/css should appear in the “status of this document”
It must include the name of the W3C group that produced the document, the type of document and its track. The name must be a link to a public page for the group.

>    This document was published by the @@@ Working/Interest Group as a Group Draft Note using the Note track.

> Include this source code:

```html
<p>This document was published by the @@@ Working/Interest Group as a Group Draft Note using the <a href="https://www.w3.org/2021/Process-20211102/#recs-and-notes">Note track</a>.</p>
```
Notice that the "include this source code" doesn't link to the CSS homepage, either. Which is correct, because this is on the Note track, so it has a `data-deliverer` instead. So this is a clear Specberus bug.

By the way, earlier when I didn't have a `data-deliverer` I got an error about it, so it looks like _both_ checks are being made here.

Found [while checking `https://www.w3.org/TR/2021/DNOTE-css-2021-20211214/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2021%2FDNOTE-css-2021-20211214%2F&profile=DNOTE&validation=simple-validation&informativeOnly=false&echidnaReady=false&patentPolicy=pp2020).

**Comment by svgeesus** [comment]
This is blocking publication, can someone take a look?

**Comment by svgeesus** [comment]
@jennyliang220 @deniak

**Comment by deniak** [comment]
@svgeesus the documentation for the rule was not up-to-date. I've just fixed it and the error should now specify the right markup to use. Sorry for the inconvenience.
