### ISSUE TITLE
Dependency versions

### ISSUE THREAD

**Issue by astorije** [w3c/specberus#148]
The version of mocha defined in `package.json` is 1.18.2. However, `npm install` installs version 2.1.0 (shown by `npm show mocha version`).

I would think that it's because version 1.18.2 might not exist in the package manager anymore but that would be pretty bad that npm would not default to the closest minor or patch version and fail if there is none. Actually, if 1.18.2 is not available, I would have thought the install would simply fail when requesting a strict version!

Anyway, I think that's a problem. Do you want to adopt the [same decision than for Echidna](https://github.com/w3c/echidna/issues/50)? Please assign the issue to me if so and I'll be glad to update the dependencies (one at a time, this time, to make sure I don't break anything).

**Comment by darobin** [comment]
I'm not sure what's going on here, but if a higher version number works perfectly well then just upgrade to it!

**Comment by astorije** [comment]
Fair enough, I'll open a PR tomorrow then!

**Comment by astorije** [comment]
My bad, `npm show mocha version` shows the latest version in the npm repository... `npm list mocha` shows the version installed. Nonetheless, I updated mocha in #150.
