### ISSUE TITLE
TAG/AB documents don't pass pubrules as they don't have charters

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#1481]
The documents published by the TAG/AB produce 2 errors:
* Could not get the document license from the API. Please make sure this group has a current charter associated with at least one document license.
* The group does not have any current charter, please contact the team contact.

The check should probably be skipped for these 2 groups.

Found [while checking `https://www.w3.org/TR/2021/NOTE-design-principles-20211216/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2021%2FNOTE-design-principles-20211216%2F&profile=NOTE&validation=simple-validation&informativeOnly=true&echidnaReady=false&patentPolicy=).

**Comment by jennyliang220** [comment]
resolved by https://github.com/w3c/specberus/pull/1508, close.
