### ISSUE TITLE
Bug in rule “headers.copyright”: exception request for security-privacy-questionnaire

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#1483]
There should be an exception on the copyright for that specification

Found [while checking `https://www.w3.org/TR/2021/NOTE-security-privacy-questionnaire-20211216/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2021%2FNOTE-security-privacy-questionnaire-20211216%2F&profile=NOTE&validation=simple-validation&informativeOnly=true&echidnaReady=false&patentPolicy=pp2020).

**Comment by jennyliang220** [comment]
Also include exceptions for DNOTE and DRY.
