### ISSUE TITLE
Inline bug reports regarding whacko that do not match whacko's documentation

### ISSUE THREAD

**Issue by astorije** [w3c/specberus#152]
- [rules/headers/dl](https://github.com/w3c/specberus/blob/c08a08b4022d34a91c4216a421665d69b8f2bc98/lib/rules/headers/dl.js#L29) says:

> `// XXX one of the horrible hacks that can be removed when whacko supports .next properly`

but [whacko seems to support it](https://github.com/cheeriojs/cheerio#nextselector).

---

- [rules/structure/h2](https://github.com/w3c/specberus/blob/8aac15c70444a9742ff7ad99239686899467735a/lib/rules/structure/h2.js) says:

> `// whacko doesn't really do .parents(selector)`

but [whacko says they do](https://github.com/cheeriojs/cheerio#parentsselector).

---

- [lib/rules/style/sheet.js](https://github.com/w3c/specberus/blob/8aac15c70444a9742ff7ad99239686899467735a/lib/rules/style/sheet.js) says:

> `// nextAll() doesn't work in whacko *cries*`

but [whacko doesn't say such thing](https://github.com/cheeriojs/cheerio#nextall).

---

@darobin, I wonder if these warnings only applied with a specific version, or in a specific use case, or similar, and they can be fixed now. If not, did you find GitHub issues regarding these problems that we can link to?
Also, if this happens because of a certain use case, any reason to think other functions in the API are likely to not work as well?

That'd be nice if we can at least document here why these are present if we cannot do anything about that.

**Comment by darobin** [comment]
What I can say is that these were all true at the time at which I wrote the code. I did not file bugs against whacko because I knew from previous discussions that the author was heading for parity and so they would become available at some point.

I would not at all be surprised if whacko now supported some or even all of the above. If so I do recommend switching to those as it eliminates code. And there's only one way to know ;)

**Comment by astorije** [comment]
Fair point @darobin, I'll dig into that, thanks!

Taking ownership of the issue, I'll close it when I can either cross out or give information about all of them.

**Comment by astorije** [comment]
Well well well, I see a hidden [bug report](https://github.com/inikulin/whacko/pull/1#issuecomment-36612617) as a comment... :P

**Comment by darobin** [comment]
Whoa, I'd completely forgotten about that!
