### ISSUE TITLE
Allow logos from https://www.w3.org/browser-logos/

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/specberus#1543]
For https://github.com/w3c/respec/pull/4080, we would like to show browser logos that hosted at https://www.w3.org/browser-logos/

Which show up as:

<img width="1068" alt="Screen Shot 2022-03-14 at 4 41 58 pm" src="https://user-images.githubusercontent.com/870154/158111894-a0c8e5e9-6a34-4b0a-8677-3cb0aa096e35.png">

Right now, Echidna gets upset because of the "not-same-folder" rule:
https://labs.w3.org/echidna/api/status?id=89ae055b-2daf-4b91-bba1-842bb8ec893f 

Cc @plehegar + @sideshowbarker (part of ClearSpec)

**Comment by deniak** [comment]
Indeed, the check seems to be too strict. @plehegar, ok to allow the use of any resources hosted on w3.org?

**Comment by jennyliang220** [comment]
Currently, all the external (not in same folder as the document) resources allowed are listed here:

https://github.com/w3c/specberus/blob/eab49a11d2bac48cbbcc3a475ff87854e2fa3088/lib/rules/links/linkchecker.js#L16-L23

**Comment by plehegar** [comment]
@deniak . Yes, it's ok. Can we use https://www.w3.org/Icons/browser-logos/ however? We're not really supposed to create top-level directories.

**Comment by marcoscaceres** [comment]
Let me know if you move them as ReSpec is currently relying on "w3.org/browser-logos/". It's a quick fix. I'll prepare a PR in the meantime.

**Comment by marcoscaceres** [comment]
Sent https://github.com/w3c/respec/pull/4093 in preparation.

**Comment by koalie** [comment]
> this should probably be moved under /Icons/browser-logos. Would that work for you or do you see a better location?

+1

**Comment by deniak** [comment]
@jean-gui reminded me that we now have a [dedicated repository](https://github.com/w3c/logos) to host logos and these logos are then uploaded to our CDN: https://cdn.w3.org/assets/logos/. I've submitted a PR https://github.com/w3c/logos/pull/1 and I'll add the CDN to the list of allowed domains.

**Comment by plehegar** [comment]
worky: https://cdn.w3.org/assets/logos/w3c/browser-logos/chrome/chrome_16x16.png

**Comment by plehegar** [comment]
bikeshed issue: https://github.com/tabatkins/bikeshed/issues/2246
