### ISSUE TITLE
Travis builds keep failing

### ISSUE THREAD

**Issue by astorije** [w3c/specberus#164]
The validation tests (like this [css validator timeout](https://travis-ci.org/w3c/specberus/jobs/53991933) or this [html validator timeout](https://travis-ci.org/w3c/specberus/jobs/53882940)) very often fails due to timeouts. This is something we don't really want in general, but so far we could ignore the errors and pretend things work fine. It is not great because I remember myself not checking a build, being sure it was a timeout error, where it wasn't...

The problem is, #158 brought automatic publication on npm after a new tag is pushed **when a build is successful**. That could be problematic, as if a build fails, the automatic publication will not kick in.

Any idea on how to beat these timeouts?

**Comment by darobin** [comment]
Why not disable validation in the test suite? And enable it with an environment variable so it runs locally.

**Comment by astorije** [comment]
That's an idea, but wouldn't be preferable to keep the entire test suite running? I am just saying that because I don't know at what level the timeouts exist.

**Comment by darobin** [comment]
Frankly, if it's just the validators failing then we can live with not running those. The primary issue would be for changes to the validator code — hopefully running the TS locally will catch that.

In fact we could reverse it. I think that Travis sets an environment variable so you know you're running there. We could use that to only disable validation there, and keep it running by default for developers.

**Comment by astorije** [comment]
Good point, I'll apply the latter, thanks. Man, you're so resourceful!
