### ISSUE TITLE
class="correction" and class="addition" NOT allowed in the SoTD

### ISSUE THREAD

**Issue by siusin** [w3c/specberus#1642]
The checker is [complaining about](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2F2022%2F09%2Fhangzhou%2Fcwig%2FREC-html-aria-20220926.html&profile=REC&validation=simple-validation&informativeOnly=false&echidnaReady=false&patentPolicy=pp2020) these two sentences even we include [the statement of candidate amendments](https://www.w3.org/2022/09/hangzhou/cwig/REC-html-aria-20220926.html#sotd).

**Comment by deniak** [comment]
The correct paragraphs, as reported by pubrules, are:
```html
<p class="correction">Candidate corrections are marked in the document.</p>
<p class="addition">Candidate additions are marked in the document.</p>
```

But there's also a problem with another paragraph.
```html
<p>
    This document was published by the <a href="https://www.w3.org/groups/wg/webapps">Web Applications Working Group</a> as
    a Recommendation using the <a href="https://www.w3.org/2021/Process-20211102/#recs-and-notes">Recommendation track</a>. It includes candidate amendments since the previous Recommendation.
  </p>
```
should be
```html
<p>
    This document was published by the <a href="https://www.w3.org/groups/wg/webapps">Web Applications Working Group</a> as
    a Recommendation using the <a href="https://www.w3.org/2021/Process-20211102/#recs-and-notes">Recommendation track</a>. It includes <a href="https://www.w3.org/2021/Process-20211102/#candidate-amendments">candidate amendments</a>, introducing substantive changes and new features since the previous Recommendation.
  </p>
```

See [html-aria.zip](https://github.com/w3c/specberus/files/9651585/html-aria.zip) if you want to make a diff

**Comment by siusin** [comment]
It works \o/ -> https://www.w3.org/TR/2022/REC-html-aria-20220927/

Thank you @deniak , I didn't know that it has to be exactly the same sentence.
