### ISSUE TITLE
Loosen the rules of dates format in the SoTD

### ISSUE THREAD

**Issue by siusin** [w3c/specberus#1649]
https://www.w3.org/pubrules/doc/rules/?profile=WD#datesFormat

@plehegar and I had a discussion on [an issue about Dates Format](https://github.com/w3c/html-aria/pull/430#issuecomment-1260967117) in the SoTD this week. We propose to loosen the dates format as long as it isn't ambiguous:

- this will only affect the dates in the header and SoTD;
- DD MM YYYY is not allowed, f.ex, 08-09-2022, 08092022;
- any date with letters is allowed, f.ex, 08-Sep-2022, 08 September 2022.

**Comment by jennyliang220** [comment]
Hi @siusin, it's possible to change the format of the dates if there's an agreement, include allowing 20220714`YYYYMMDD` used in [this PR](https://github.com/w3c/html-aria/pull/430/commits/b9e401225750ade1070d3608c92aa295dff6429e)

The major date formats are mentioned in [Wikipedia](https://en.wikipedia.org/wiki/Date_format_by_country):

- ~~day–month formats such as "5 October 2022" (05/10/22, 05/10/2022, 05-10-2022 or 05.10.2022)~~ **not allowed as mentioned [above](https://github.com/w3c/specberus/issues/1649#issue-1398063847)**
- month–day formats such as "October 5, 2022" (10/05/22 or 10/05/2022)
- The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format YYYY-MM-DD (2022-10-05)

...however, there are more cases mentioned in [this Oracle doc](https://docs.oracle.com/cd/E41183_01/DR/Date_Format_Types.html). Pubrules currently accept `D Month Yr`(variation of Line J in [doc](https://docs.oracle.com/cd/E41183_01/DR/Date_Format_Types.html)).
@plehegar @deniak any ideas?

**Comment by deniak** [comment]
> https://www.w3.org/pubrules/doc/rules/?profile=WD#datesFormat
> 
> @plehegar and I had a discussion on [an issue about Dates Format](https://github.com/w3c/html-aria/pull/430#issuecomment-1260967117) in the SoTD this week. We propose to loosen the dates format as long as it isn't ambiguous:
> 
>     * this will only affect the dates in the header and SoTD;

Where would such date format appear in the header? Also, it seems odd to allow this new format in the SotD but not in the rest of the document. Currently, the rule checks the data format in the whole document.

> 
>     * DD MM YYYY is not allowed, f.ex, 08-09-2022, 08092022;
> 
>     * any date with letters is allowed, f.ex, 08-Sep-2022, 08 September 2022.

We should be able to update the regex to allow this format.

**Comment by siusin** [comment]
If I understand correctly,  @plehegar agreed we shouldn't check the dates format in other parts of the document except for the SoTD and the header, it's up to the Editors to decide which dates format they prefer in the content.
