### ISSUE TITLE
Errata link should be optional; can be inline

### ISSUE THREAD

**Issue by svgeesus** [w3c/specberus#1665]
Pubrules [requires an errata link](https://www.w3.org/pubrules/doc/rules/?profile=REC#docIDOrder) for Recommendations:

> Errata - URI to an errata document for any errors or issues reported since publication. See also suggestions on [errata page structure](https://www.w3.org/2001/06/manual/#Errata) in the Manual of Style. Note: Do not put the errata document in TR space as the expectation is that we will not modify document in TR space after publication; see the policy for [in-place modification of W3C Technical Reports](https://www.w3.org/2003/01/republishing/).

However, we now have the option of Recommendation with Candidate/Proposed Corrections, which are effectively inline Errata.

@frivoal suggested to me that it should be possible to use alternate wording:

> Yeah, that’s annoying. Do you think you could file a bug against pubrules, to get them to accept a sentence like ”<a href=["https://www.w3.org/Consortium/Process/#errata"](https://www.w3.org/Consortium/Process/#errata)>errata</a> will be tracked inline in this document” as an alternative to the link?

**Comment by jennyliang220** [comment]
Hi @plehegar , is it ok for Pubrules to add the errata description? 
cc @deniak

**Comment by deniak** [comment]
We actually have a way to distinguish regular RECs to RECs with Candidate/Proposed changes. I think it makes sense to make the errata optional for the latter.

**Comment by plehegar** [comment]
This makes sense to me.
