### ISSUE TITLE
Remove legacy copyright rule in Feb 2023

### ISSUE THREAD

**Issue by jennyliang220** [w3c/specberus#1686]
https://github.com/w3c/specberus/pull/1685/files add new copyright rule for 2023 W3C Inc., but still uses the legacy one in 2022. Jan would be a transition area when both copyrights are allowed.

Delete every legacy copyright mentioned in https://github.com/w3c/specberus/pull/1685/files, marked as 'TODO:'

**Comment by deniak** [comment]
Fixed by https://github.com/w3c/specberus/pull/1700
