### ISSUE TITLE
Bug in rule “headers.copyright”: Rejects the required source code

### ISSUE THREAD

**Issue by svgeesus** [w3c/specberus#1690]
In a Bikeshed-generated WD, the checker complained about the copyright statement, which is _fair enough_ because the [PR on Bikeshed for copyright update](https://github.com/tabatkins/bikeshed-boilerplate/pull/30) has not yet been merged.

The checker gives exact source code to use, and the correct one (new copyright, permissive license) was pasted in from the checker (line breaks added below for readability):

```html
<p class="copyright"><a href="https://www.w3.org/Consortium/Legal/ipr-notice#Copyright">Copyright
</a> © 2023 <a href="https://www.w3.org/">World Wide Web Consortium</a>. 
<abbr title="World Wide Web Consortium">W3C</abbr><sup>®</sup> 
<a href="https://www.w3.org/Consortium/Legal/ipr-notice#Legal_Disclaimer">liability</a>, 
<a href="https://www.w3.org/Consortium/Legal/ipr-notice#W3C_Trademarks">trademark</a> and 
<a href="https://www.w3.org/Consortium/Legal/copyright-software">permissive document 
license</a> rules apply.</p>
```
I still get the exact same error message, implying that the checker is not actually checking for that exact string but for something else?? Maybe the older proposal with "W3C, Inc." ??

Found [while checking `https://www.w3.org/TR/2023/WD-css-images-4-20230112/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2023%2FWD-css-images-4-20230112%2F&profile=WD&validation=simple-validation&informativeOnly=false&echidnaReady=false&patentPolicy=pp2020).

cc/ @tabatkins @fantasai

**Comment by deniak** [comment]
Pubrules reports the following error:
```
Could not get the document license from the API. Please make sure this group has a current charter associated with at least one document license.
```

The [CSS WG charter has expired](https://www.w3.org/groups/wg/css/charters) so pubrules is unable to fetch the [group's license](https://www.w3.org/2020/12/css-wg-charter.html#licensing) and check the copyright.
Pubrules should pass as soon as the charter is extended.

**Comment by svgeesus** [comment]
Thanks, I also just found that the approved charter has not been sent out. I agree that this will fix it.
