### ISSUE TITLE
Bug in rule “sotd.pp”: Required source code is rejected

### ISSUE THREAD

**Issue by svgeesus** [w3c/specberus#1691]
The checker wants specific source code for the patent policy statement (line breaks added below, for legibility.

```html
<p>This document was produced by a group operating under the 
<a href="https://www.w3.org/Consortium/Patent-Policy/">W3C Patent Policy</a>. 
W3C maintains a <a rel="disclosure" href="@@URI to IPP status or other page@@">
public list of any patent disclosures</a> made in connection with the deliverables of the group; 
that page also includes instructions for disclosing a patent. An individual who has actual knowledge 
of a patent which the individual believes contains 
<a href="https://www.w3.org/Consortium/Patent-Policy/#def-essential">Essential Claim(s)</a> must 
disclose the information in accordance with 
<a href="https://www.w3.org/Consortium/Patent-Policy/#sec-Disclosure">section 6 of the W3C Patent Policy</a>.</p>
```

I pasted that exact code into a document, updating to the actual disclosure page **https://www.w3.org/groups/wg/css/ipr** but the checker still rejects it.

Found [while checking `https://www.w3.org/TR/2023/WD-css-images-4-20230112/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2023%2FWD-css-images-4-20230112%2F&profile=WD&validation=simple-validation&informativeOnly=false&echidnaReady=false&patentPolicy=pp2020).

**Comment by deniak** [comment]
Like #1690, this is also related to the expired charter of the group. The patent policy is provided by the charter and since there's no active charter, pubrules is not able to find the expected PP
