### ISSUE TITLE
profile=auto not working in the REST API (for some documents)

### ISSUE THREAD

**Issue by pchampin** [w3c/specberus#1701]
E.g. https://www.w3.org/pubrules/api/validate?url=https://www.w3.org/TR/2022/WD-rdf-canon-20221124/&profile=auto

responds with

```json
{"success":false,"errors":["Without a profile there is nothing to check."],"warnings":[],"info":[],"metadata":{}}
```

This depends on the document you pass (the example from the README does work...).

**Comment by deniak** [comment]
@pchampin thanks for the report. There was a bug with one of the promise which should now be fixed.
