### ISSUE TITLE
Allow alternative sentence for (Draft) Notes.

### ISSUE THREAD

**Issue by jennyliang220** [w3c/specberus#1705]
For (Draft) Notes, allow both sentence:

- This Group (Draft )?Note is endorsed by the XXX Group, but is not endorsed by W3C itself nor its Members.
- Group (Draft )?Notes are not endorsed by W3C nor its Members.

related to https://github.com/w3c/tr-design/issues/288.

**Comment by fantasai** [comment]
@jennyliang220 When you get this implemented, can you follow up with ReSpec and Bikeshed to have the first one applied by default to Notes and the second one applied by default to Draft notes?

**Comment by jennyliang220** [comment]
resolved by https://github.com/w3c/specberus/pull/1707
