### ISSUE TITLE
Validator incorrectly claims "menu" role is invalid

### ISSUE THREAD

**Issue by svgeesus** [w3c/specberus#1706]
Trying to publish the FPWD of web animations 2, I get [194 html validation errors](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2023%2FWD-web-animations-2-20230221%2F&profile=FPWD&validation=simple-validation&informativeOnly=false&echidnaReady=false&patentPolicy=pp2020) which is way too many to fix manually on generated html.

Most of them are

> Bad value “menu” for attribute “role” on element “aside”.

This is correct html, and the validator is wrong.

  [menu role](https://w3c.github.io/aria/#menu) linked from [4.3 Managing Focus and Supporting Keyboard Navigation](https://w3c.github.io/aria/#managingfocus_authors)

**Comment by xfq** [comment]
This should probably be filed against https://github.com/validator/validator/issues

**Comment by nschonni** [comment]
https://github.com/speced/bikeshed/issues/2476#issue-1588918973

**Comment by annevk** [comment]
Indeed, the validator is correct. Bikeshed is wrong.

**Comment by svgeesus** [comment]
Ah, cheers for filing that. Easy fix then.
