### ISSUE TITLE
Specberus rejects documents linking to the W3C's darkmode stylesheet

### ISSUE THREAD

**Issue by tabatkins** [w3c/specberus#1739]
The [dark-mode stylesheet](https://www.w3.org/StyleSheets/TR/2016/dark.css) has to be loaded after the [base stylesheet](https://www.w3.org/StyleSheets/TR/2016/base.css), because the darkmode sheet sets colors with a `:root` selector that needs to override the `:root` selector in the base sheet.

However, Specberus rejects documents doing this:

```
Specberus Errors:
694    W3C TR style sheet must be last.
695      { name: 'style.sheet', section: 'metadata', rule: 'lastStylesheet' }
696  
697  Details: https://labs.w3.org/echidna/api/status?id=f37a4708-ff03-407a-a3c2-b967abaf0fe2
698  💥 Echidna publish has failed.
```

Either Specberus needs to allow the W3C's darkmode styles to come after base, or the darkmode sheet needs to have its selector adjusted so it'll override regardless of load order.

**Comment by tabatkins** [comment]
Note that the logo links in the 2021 stylesheet don't work.

**Comment by deniak** [comment]
> Note that the logo links in the 2021 stylesheet don't work.

Indeed, the files were missing. This is now fixed and the patch for the dark mode stylesheet has been deployed.
Thanks for the report.
