### ISSUE TITLE
Copyright checker doesn't accept current copyright URL

### ISSUE THREAD

**Issue by tabatkins** [w3c/specberus#1746]
Specberus complains if you use the current dated copyright URL (https://www.w3.org/Consortium/Legal/2023/software-license), but allows both the undated URL (https://www.w3.org/Consortium/Legal/copyright-software) and the *previous* dated URL which is no longer in force (https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document). This caused some publication failures when someone updated Bikeshed's W3C boilerplates to use the new dated URL (https://github.com/speced/bikeshed-boilerplate/issues/44).

I've just updated the boilerplates to use the undated URL, so the Bikeshed issue should be resolved, but the checker needs to be updated to accept the new dated URL and *stop* accepting the old one.

**Comment by deniak** [comment]
Thanks for the report. This was clearly an oversight which should be fixed now.
