### ISSUE TITLE
CR pub fails due to spurious "missing transition request" issue

### ISSUE THREAD

**Issue by tabatkins** [w3c/specberus#1770]
We're trying to publish CSS View Transitions as a CR, which we already have approval for in the transitions repo: <https://github.com/w3c/transitions/issues/561>

However, [Specberus is failing](https://labs.w3.org/echidna/api/status?id=cf261f5c-6ac3-4fae-8075-37c679bb2df8) with the following message:

```
"transition-checker": {
        "status": "error",
        "errors": [
          "Error: Issue not found on the github repository w3c/transitions. Make sure all the requirements are met: https://github.com/w3c/echidna/wiki/CR-publication-workflow#request-a-transition-request"
        ]
      }
```

We have no idea what this check is actually asking for.

**Comment by fantasai** [comment]
See https://wiki.csswg.org/spec/publish#step-by-step-publishing-a-css-spec ; for CR you need to file an issue in the Transitions repo, you can't publish it yourself. https://github.com/w3c/transitions

**Comment by tabatkins** [comment]
Yes, that issue is already filled and linked in the original post. It was approved last week.

**Comment by fantasai** [comment]
I believe at this point the Team needs to handle the publication.

**Comment by deniak** [comment]
The list of requirements to publish CR with echidna is listed [here](https://github.com/w3c/echidna/wiki/CR-publication-workflow).
In this case, @plehegar needs to update his comment to 'Transition approved.' and the team contact needs to send a draft announcement to the communication team. Once reviewed, they will then comment 'draft transition received.'.
With these 2 comments, echidna will be able to detect that the transition has been approved.

**Comment by tabatkins** [comment]
The templates should be changed, then - currently it defaults the issue title to "CR Request for `<title>`", which suggests that what Khushal wrote was correct, rather than putting the shortname.

**Comment by svgeesus** [comment]
So the [existing comment](https://github.com/w3c/transitions/issues/561#issuecomment-1674799689) "Approved" isn't good enough and it needs the exact string "Transition approved."?

**Comment by svgeesus** [comment]
> and the team contact needs to send a draft announcement to the communication team.

OK, on it.

**Comment by svgeesus** [comment]
> <html><body>
<p>
  "Some more information is needed before your document can be generated.
  Initial values may have been set automatically for some items, but
  please check to make sure they are correct."
</p>

<form action="/new-doc-from-template">
<p>
  
  

  
</p>



SpecName |  
-- | --
DocumentURI |  
TransitionRequestURI |  
FeedBackDueDate |  
GroupName |  
DisclosurePageURI |  
Team Contact Name

</form>
</body>
</html>

However, for an automatic publication, `DocumentURI` is not known with any exactitude because it depends on which day the comm team adds the label that the draft is okay. I supose I will make an educated guess of this Monday.

Has this procedure been, like, tested by someone?

**Comment by svgeesus** [comment]
Please try again. I have:

- edited the transition request title to be what specberus expects
- updated the .bs to have the correct status, review end date
- asked, and got, plh to change the "transition approved" message

Please report here if it fails again.

**Comment by svgeesus** [comment]
@tabatkins who was doing the specberus publication, when it failed?

**Comment by tabatkins** [comment]
Khushal

**Comment by svgeesus** [comment]
@khushalsagar  do you want to try again, or would you rather I do it manually?

**Comment by khushalsagar** [comment]
@svgeesus happy to have you do it.

**Comment by svgeesus** [comment]
publication requested (manually) 3 Sept expected 5 Sept

**Comment by svgeesus** [comment]
I'm still interested to see if automatic CR publication works, but also unwilling to hold up a CR publication until after TPAC just to find out. Someone else can be the guinea-pig for this.

**Comment by deniak** [comment]
Hi Chris,

I think you now have all the requirements to publish that document with echidna.
All you need to do is to:
* [generate a token](https://www.w3.org/publications/token-register/) (link restristed to chairs and team contacts) for the spec https://www.w3.org/TR/css-view-transitions-1/
* update the date on the editor's draft to match the current day
* prepare a [manifest listing all the related files](https://github.com/w3c/echidna/wiki/Preparing-your-document#example-of-manifest) and upload it under https://drafts.csswg.org/css-view-transitions-1/:
```
index.html
diagrams/desktop-browser-snapshot-root.svg
diagrams/desktop-browser.svg
diagrams/phases/phases.html
diagrams/phases/script.js
diagrams/phone-browser-scrolled-to-top-with-url.svg
diagrams/phone-browser-scrolled-to-top-without-url.svg
diagrams/phone-browser-snapshot-root.svg
diagrams/phone-browser-with-url.svg
diagrams/phone-browser-without-url.svg
diagrams/phone-browser.svg
diagrams/resources/scaler.js
diagrams/resources/slides.js
diagrams/videos/bad-sidebar.mp4
diagrams/videos/circle.mp4
diagrams/videos/default.mp4
diagrams/videos/good-sidebar.mp4
diagrams/videos/header.mp4
diagrams/videos/slide.mp4
diagrams/videos/slow.mp4
```

Once it's done, you can trigger the request to echidna with the following command:
```
curl 'https://labs.w3.org/echidna/api/request' --data 'url=<pathToTheManifest>&decision=<decisionUrl>&token=<token>
```

**Comment by svgeesus** [comment]
[Published (manually) 5 Sept](https://www.w3.org/TR/2023/CR-css-view-transitions-1-20230905/)
