### ISSUE TITLE
Allow multiple WGs in stability text (CR)

### ISSUE THREAD

**Issue by himorin** [w3c/specberus#1818]
In current CR publication, [stability section](https://www.w3.org/pubrules/doc/rules/?profile=CR#stability) requirement explicitly requires a text as:

> has commitments from Working Group members to royalty-free licensing for implementations.

which restricts 'Working Group' as a single form. For joint deliverable, plural form is desired here, like 'Working Groups members' or 'members of Working Groups'.

/cc @plehegar

**Comment by deniak** [comment]
@himorin can you give it another try please?

**Comment by himorin** [comment]
@deniak hi Denis, I've edited (not by bikeshed but manual change on generated spec) and checked with pubrules, but I've got error at stability section.
https://www.w3.org/pubrules/?url=https%3A%2F%2Fdas.w3c.himor.in%2FCR-orientation-event-20240320b.html&profile=CR&validation=simple-validation&informativeOnly=false&echidnaReady=false&patentPolicy=pp2020

It says `No stability warning paragraph. Expected text: ` but not has a line of `Joint publication detected.` which is included in patent policy check part. 
Even adding ` data-deliverer="43696, 114929"` to `<p>` for `This document was published by ...` part, it does not work.

Could you kindly check?

**Comment by deniak** [comment]
@himorin sorry, there was indeed a bug with my last patch. This is now fixed and the document passes the stability rule now.
