### ISSUE TITLE
Discourage HTTP with warning messages, or support only HTTPS

### ISSUE THREAD

**Issue by tripu** [w3c/specberus#184]
> _&ldquo;We could change pubrules to require all resources loaded by our TR documents to be loaded off HTTPS (or relative). It's a relatively easy check to add, and it wouldn't be very disruptive. At least this would ensure that content from now on is ready.&rdquo;_

&mdash;&nbsp;W3C Team wiki.

Seems likely to happen; either encouraging HTTPS at first, maybe banning insecure HTTP altogether in the end.

See w3c/echidna#145

**Comment by mikewest** [comment]
I regret that I have only two :+1:'s to give.

**Comment by plehegar** [comment]
Here is the proposal:
https://lists.w3.org/Archives/Public/spec-prod/2016AprJun/0024.html

**Comment by jennyliang220** [comment]
Currently, **previous link** is the only link in headers that allows http, we could change that.

```
const prevRex = /^http(s?):\/\/www\.w3\.org\/TR\/\d{4}\/[A-Z]+-(.+)-(\d{8})\/$/;
```

**Comment by jennyliang220** [comment]
Issues found when updating the project to `https`:

1. https://www.w3.org/2005/05/tr-versions/ 404. with or without `https://`
2. The charter in API data for `headers/ig-note.html'` is `http://`, which fails the check and breaks test. Need update?
