### ISSUE TITLE
Support for multi-groups publications

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/specberus#186]
Right now, specberus doesn't support publications delivered by more than one groups; that means such publications (which are relatively frequent nowadays) can't be published via Echidna.

An example of such a publication would be http://www.w3.org/TR/2015/WD-mediacapture-depth-20150129/

**Comment by darobin** [comment]
Should we enforce a typical structure for multiple-group publications? For instance, ReSpec will always use the same markup, scaling it to `n` groups. We could rely on that, or a variant of it.

**Comment by astorije** [comment]
I'd like typical structure for this indeed.

So this issue requires work on Specberus and Echidna, but IMO it also requires work (and decisions) on our internal system to (the one Echidna is calling to publish under `/TR/`). I'll reopen the discussion to make this move forward.

**Comment by darobin** [comment]
I know this involves talking across a bunch of moving parts, but maybe you should post to spec-prod to open a discussion about using a set style for this?
