### ISSUE TITLE
CRD publication fails due to "wrong-w3c-state-link" error

### ISSUE THREAD

**Issue by anssiko** [w3c/specberus#1887]
@deniak Specberus publication started failing with wrong-w3c-state-link error. It looks the trailing slash at the end of the w3c-state-link URL is the culprit. However, we haven't changed our [workflow](https://github.com/webmachinelearning/webnn/tree/main/.github/workflows) or [bikeshed-boilerplate](https://github.com/speced/bikeshed-boilerplate/tree/main/boilerplate/webmlwg). Failure first noticed after this commit: https://github.com/webmachinelearning/webnn/commit/d1d71ede14cbb59a4a84dc6f1dbdffe34c2a6d09

TR fails to deploy: https://www.w3.org/TR/webnn/
ED builds properly: https://webmachinelearning.github.io/webnn/

> Specberus Errors:
>     The link for text "W3C Candidate Recommendation Draft" should pointing to W3C profile "https://www.w3.org/standards/types#CRD", but the link found in the document is "https://www.w3.org/standards/types/#CRD".
>       {
>         name: 'headers.w3c-state',
>         section: 'front-matter',
>         rule: 'dateState'
>       }
>   
>   Details: https://labs.w3.org/echidna/api/status?id=9b0f3878-e95d-48a2-a965-b55dc66c87de

Your Specberus-fu welcome!

**Comment by Ms2ger** [comment]
Ref https://github.com/speced/bikeshed/pull/2937

**Comment by anssiko** [comment]
@deniak this looks like a Link Checker and Specberus interop issue. Which one is right? The former passes while the latter fails. If Link Checker is correct, I think a Specberus fix might be: 

```diff
-       const expectedLink = `https://www.w3.org/standards/types#${hash}`;
+       const expectedLink = `https://www.w3.org/standards/types/#${hash}`;

```

https://github.com/w3c/specberus/blob/1e009e0b61d7a2fbe14c7fa14155d609541a66f7/lib/rules/headers/w3c-state.js#L58

**Comment by kainino0x** [comment]
I just finally debugged to figure out this is why WebGPU's publish-to-TR step is failing.

IMO the version with the `/` is better, as
`https://www.w3.org/standards/types` 301 redirects to
`https://www.w3.org/standards/types/`.

Would love to see this fixed! I would open a PR with Anssi's fix, however I don't know if simply updating that line will break a bunch of other projects?

**Comment by anssiko** [comment]
I believe the fix with tests just landed in https://github.com/w3c/specberus/pull/1889 -- thanks @deniak!

**Comment by kainino0x** [comment]
Just re-ran the publish job for <https://www.w3.org/TR/webgpu/> and it worked! Thank you!

**Comment by anssiko** [comment]
Similarly, I can confirm https://www.w3.org/TR/webnn/ publish workflow is green again.

Thanks a bunch @deniak! I'll close this issue.
