### ISSUE TITLE
Bug in rule “headers.w3c-state”: Placeholder link for Discontinued Draft

### ISSUE THREAD

**Issue by svgeesus** [w3c/specberus#1896]
The pubrules checker looks to be using an unfinished, placeholder URL for the status of Discontinued Drafts:

```
Incorrect w3c status element, <p id="w3c-state">. <p id="w3c-state">
[W3C @@Profile](https://www.w3.org/standards/types#@@Profile), DD Month YYYY</p>.
```
I'm guessing that **#W3C @@Profile** is not the intended link.

What seems to be the correct fragment does exist

https://www.w3.org/standards/types/#DISC

Found [while checking `https://www.w3.org/TR/2024/DISC-RangeRequest-20241210/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2024%2FDISC-RangeRequest-20241210%2F&profile=DISC&validation=simple-validation&informativeOnly=false&echidnaReady=false&patentPolicy=pp2020).

**Comment by deniak** [comment]
Hi Chris,

As noted in [the pubrules documentation](https://www.w3.org/pubrules/doc/rules/?profile=DISC#dateState), the status for that kind of documents is 'Discontinued draft' instead of 'Discontinued Working Draft'.

I updated the document and the checks pass now.
