### ISSUE TITLE
HTTP parameter “profile” isn't used to select appropriate value in drop-down menu

### ISSUE THREAD

**Issue by tripu** [w3c/specberus#194]
eg, load [`https://labs.w3.org/pubrules/?url=http%3A%2F%2Fwww.w3.org%2FTR%2F2014%2FREC-exi-profile-20140909%2F&profile=REC&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004&processDocument=2014`](https://labs.w3.org/pubrules/?url=http%3A%2F%2Fwww.w3.org%2FTR%2F2014%2FREC-exi-profile-20140909%2F&profile=REC&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004&processDocument=2014).

Although the profile is set to `REC` in the URL, the drop-down menu labeled &ldquo;profile&rdquo; in the page stays set at &ldquo;working draft&rdquo; (the first enabled item).

**Comment by astorije** [comment]
Should that be part of the UI refactoring that @darobin intends to do?

**Comment by darobin** [comment]
Yes, it seems to be badly needed :(
