### ISSUE TITLE
Update socket.io and superagent

### ISSUE THREAD

**Issue by astorije** [w3c/specberus#197]
[David](https://david-dm.org/w3c/specberus) reports that these two are very much outdated:

- [x] [socket.io](https://www.npmjs.com/package/socket.io): we require `^0.9.17`, current stable is `	1.3.5`
- [x] [superagent](https://www.npmjs.com/package/superagent): we require `^0.17.0`, current stable is `1.2.0`

I looked a bit and because of incompatibility, updating these is not as simple as just editing `package.json`. @darobin, could you give a hand in updating these please?

**Comment by darobin** [comment]
I can take this over if you want, but I might not be able to get to it promptly. How urgent is it?

**Comment by astorije** [comment]
Not urgent, just a reminder that these 2 are waiting.

**Comment by astorije** [comment]
socket.io upgraded in #198.

**Comment by tripu** [comment]
Both dependencies updated successfully to their latest versions after recent PRs (#214, #217, #219).
