### ISSUE TITLE
Allow exceptions on a per specification basis

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#208]
The CSS WG intends to publish specifications containing example using values (not checked yet by the validator) defined in the specification.

Specberus should be able send warnings instead of errors if an exception has been granted for a specification (CSS copyright, copyrights, IPP, etc). See also #18 and #19.

**Comment by plehegar** [comment]
Here is what I intend to do here: add a json spec config file where, for a given short name, it contains an array of exceptions per rule. If the regex contained in the exception matches the error message generated by the rule, then transform that error into a warning before continuing.

**Comment by plehegar** [comment]
https://github.com/w3c/specberus/pull/261

**Comment by tripu** [comment]
Closed via #261.
