### ISSUE TITLE
results not consistent when using the history API

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#224]
We have inconsistent results when using the history API. To reproduce the bug:
- go to https://labs.w3.org/pubrules/
- enter https://labs.w3.org/spec-generator/?type=respec&url=https://w3c.github.io/webdriver/webdriver-spec.html?specStatus=WD;shortName=webdriver in the url field and check "Check that the document is valid for automatic publication with Echidna"
- submit the form
- compare the result with https://labs.w3.org/pubrules/?url=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%3A%2F%2Fw3c.github.io%2Fwebdriver%2Fwebdriver-spec.html%3FspecStatus%3DWD%3BshortName%3Dwebdriver&profile=WD-Echidna&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=true&patentPolicy=pp2004&processDocument=2014

**Comment by tripu** [comment]
(Part of a larger issue. See #194 and #206.)

**Comment by deniak** [comment]
Duplicate of issue #206
