### ISSUE TITLE
Publishing tags to npm via Travis builds is failing

### ISSUE THREAD

**Issue by tripu** [w3c/specberus#237]
Automatic publication [to npmjs.org](https://www.npmjs.com/package/specberus) has failed at least for the last three tags (it's `1.2.0` on npmjs.org because I published manually from my command line). See [the log of the last attempt, line 475](https://travis-ci.org/w3c/specberus/jobs/77679671):

> NPM API key format changed recently. If your deployment fails, check your API key in ~/.npmrc.
> http://docs.travis-ci.com/user/deployment/npm/

So I wanted to try to encrypt our npm key again. I've tried (again) to install [the Travis CI client](https://github.com/travis-ci/travis.rb) on my laptop, and also on a personal server of mine. It still fails to me with these messages:

```bash
$ sudo gem install travis -v 1.8.0 --no-rdoc --no-ri
Building native extensions.  This could take a while...
ERROR:  Error installing travis:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from extconf.rb:4:in `<main>'


Gem files will remain installed in /var/lib/gems/1.9.1/gems/ffi-1.9.10 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/ffi-1.9.10/ext/ffi_c/gem_make.out
```

So I'm stuck there.

I'm not even sure we need to encrypt our key differently to fix this issue &mdash; can't see what has changed recently in [the documentation and examples](http://docs.travis-ci.com/user/deployment/npm/)&hellip;

Any ideas?

Assigning to you, @deniak, to ask you to check if *you* can run the Travis CI client OK to encrypt the key&hellip;

**Comment by astorije** [comment]
@tripu, what happened is that npm changed their API key format, and therefore Travis CI fails as it's expecting a different key. I had the similar issue [recently](https://github.com/astorije/chai-immutable/commit/d04778447fcbe778a2e41af3dfcc1aeca37e006d).

Your issue seems to be Ruby related because you must not have the dev version of it (equivalent of python-dev and others in so many languages). Try running the following and then installing the travis gem again:

```
sudo apt-get install ruby-dev
```

**Comment by astorije** [comment]
Oh by the way, this resource helped me: https://github.com/npm/npm/issues/8970#issuecomment-122854271 :)

**Comment by tripu** [comment]
Thanks, @astorije!
I messed around for a while with APT again, and this time I managed to install `ruby-dev` and other dependencies, and the Travis command-line client.
Indeed, that is all I needed to re-encrypt the token and update the Travis config.

**Comment by astorije** [comment]
Glad it helped :-)
