### ISSUE TITLE
ISBN detected as date

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#260]
From [Bert's whishlist](https://lists.w3.org/Archives/Public/public-pubrules-comments/2015Sep/0000.html)

> Specberus found an ISBN number and thought it was a date...
>
> Ad 4) The number "978-1-4503-1116-8" generated:
>
>    "key": "wrong",
>    "extra": {
>      "text": "8-1-4503"
>    },
>    "type": "heuristic.date-format"
>
> I assume that means it was trying to check for ambiguous dates...

**Comment by tripu** [comment]
Duplicate (a particular case) of #178.
