### ISSUE TITLE
Group heuristic: multiple matches

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#269]
The current deliverer metadata extraction looks for all the links in the document in the document with a specific pattern.
This could be a problem if the pattern is found at different places with different links, e.g. http://w3c.github.io/manifest/index.html
```
      "deliverers": [
        {
          "homepage": "http://www.w3.org/WebPlatform/WG/",
          "name": "Web Platform Working Group"
        },
        {
          "homepage": "https://www.w3.org/WebPlatform/WG/",
          "name": "Web\n            Platform Working Group"
        }
      ],
```

We need a clear way of identifying the deliverer of a spec (`data-` attribute like we have for editors?).

We could improve the data extraction by looking only at the SotD as well but it wouldn't solve the issue.

**Comment by tripu** [comment]
`data-` attributes are simple, avoid ambiguities and make our lives easier.
WDYT, @plehegar?

**Comment by deniak** [comment]
Closing. We are now extracted the group id instead of its name and homepage.
