### ISSUE TITLE
Exceptions on specific errors instead of a whole rule

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#274]
Exceptions are currently per rule. It would be good to have more granularity and check for specific errors.

**Comment by plehegar** [comment]
Well, I proposed to filter on message text or line number but it got rejected. There is nothing to filter on at the moment.

**Comment by tripu** [comment]
I still think that trying to match chunks of natural language (the messages intended for human users of the validators) would be a bad idea, [for many reasons](https://github.com/w3c/specberus/pull/212#issuecomment-123181373).

I don't remember opposing line numbers; they seem a bit more healthy (although, iiuc, a small edit at the beginning of a document could shift all line numbers, ruin all the exceptions associated to specific line numbers, and require an edit and redeployment of `exceptions.json`&hellip;).

If some exceptions are going to need more granularity, we could use the `context` and `line`. fields. In the case of the CSS checker, the `context` is not always given. But you can see a few examples in [the JSON output](https://jigsaw.w3.org/css-validator/validator?uri=http%3A%2F%2Fwww.ibm.com%2F&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en&output=json).

Maybe this is a non-issue: is that needed for any of these CSS specs now?

**Comment by jennyliang220** [comment]
Close this issue for now, because currently there's no demand to just add one detailed rule to exception.

```
"^webrtc$": [
    {
      "rule": "headers.copyright"
    }
  ],
```
would be enough for now.
