### ISSUE TITLE
Check against inconsistencies in URLs of this/previous/latest versions

### ISSUE THREAD

**Issue by astorije** [w3c/specberus#29]
Two related checks:

1. [x] Check against inconsistency when *previous version URI* ≠ *redirected latest version URI*.
2. [x] *This version URI* ≠ *previous version URI*.

**About the first one:**

- **OK** when Previous Version of the document to be published == the document behind the Latest Version
- **FAILURE** otherwise.

Edge cases:

- Once the document is published, this rule cannot return OK anymore.
- PER: after publication, the Latest Version must not change (point to the REC rather than the published PER).

Hopefully I will come up with a PR someday, but I want to agree on a decision before anyway.

**About no. 2:**

Echidna [has published (wrongly) already a spec with *this version URI* = *previous version URI*](http://www.w3.org/TR/2015/WD-appmanifest-20150317/).

**Comment by plehegar** [comment]
Feel free to assign an issue to me in echidna for this case to be tested once this issue is resolved.

**Comment by astorije** [comment]
I do not recognize my *hand*-writing in what is written in the original issue so I'm assuming its content was changed and refactored. I decline property of this issue then :-)

Due to GitHub being flexible here and its lack of history for issues, let's please not edit each other's comments besides small typos.

**Comment by tripu** [comment]
@astorije Yes, I edited the title & description of the issue to make it clearer&nbsp;&mdash;or so I thought&mdash;, and to accommodate that new bug that is closely related&hellip; I was careful and kept almost all your wording. But I'm sorry if that confused things. Because there's no history of those changes as you say, maybe we should add comments (even if they change the meaning of the issue altogether), yes&hellip;

**Comment by marcoscaceres** [comment]
Hey, not sure where to file this, but I the manifest spec was affected by this bug: 

http://www.w3.org/TR/2015/WD-appmanifest-20150317/

Is it possible to fix that for the spec above? I've had someone report it to me.

**Comment by tripu** [comment]
Yes, @marcoscaceres&nbsp;&mdash;&nbsp;that spec was precisely the one that brought this bug to @deniak's attention.

I see that there have been already a few versions published after that one, so I'm assuming you are using the system OK again now&hellip;?

About correcting the &ldquo;previous version&rdquo; link for that particular version, I guess that is the right thing to do here, and it'll take just a minute. But I'm pinging @astorije (ping!) here first, to make sure it's OK if I do that myself now, manually.

**Comment by marcoscaceres** [comment]
On Tuesday, April 14, 2015, tripu <notifications@github.com> wrote:

> Yes, @marcoscaceres <https://github.com/marcoscaceres> — that spec was
> precisely the one that brought this bug to @deniak
> <https://github.com/deniak>'s attention.
>
> I see that there have been already a few versions published after that
> one, so I'm assuming you are using the system OK again now…?
>

Absolutely. Works great!


> About correcting the “previous version” link for that particular version,
> I guess that is the right thing to do here, and it'll take just a minute.
> But I'm pinging @astorije <https://github.com/astorije> (ping!) here
> first, to make sure it's OK if I do that myself now, manually.
>

Thanks!
