### ISSUE TITLE
Style RFC2119 keywords

### ISSUE THREAD

**Issue by tripu** [w3c/specberus#293]
cf. [RFC2119](https://tools.ietf.org/html/rfc2119).

ie, in bold, underlined with a dotted line.
Use `<span class="rfc2119">`?
The old pubrules checker does this.

Also, `grep` `lib/l10n-??_??.js` to find all missing instances and wrap in `span` conveniently.

**Comment by tripu** [comment]
I want to style those words in `lib/lib/l10n-en_GB.js` too, @deniak. Isn't that right?

**Comment by deniak** [comment]
To me, `l10n-en_GB.js` contains errors/warnings. The SHOULD/MUST/... aren't not necessarily the key words defined in the RFC. Plus, when there's an error, the description of the rule is already displayed in the UI so it'll just be redundant.

**Comment by tripu** [comment]
OK @deniak.
