### ISSUE TITLE
Links in the header of the document should use 'http'

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#307]
**For the moment**, links in the header shouldn't use `https`

**Comment by dontcallmedom** [comment]
While I understand there is an ongoing discussion for the "latest version" URL, do we really need to enforce the http:// scheme for the previous / this version URLs (even temporarily)?

**Comment by deniak** [comment]
If we don't enforce a specific protocol, I'm afraid we'll end up with a mix of `http` and `https` links on /TR. I don't think it's harmful but I'd favour consistency.
In the [recent discussions](https://lists.w3.org/Archives/Team/webreq/2016Mar/0095.html) with @plehegar, we are leaning towards having relative urls in TR documents. It's now just a matter of how and when.

**Comment by deniak** [comment]
Proposal: use https everywhere. @plehegar will bring the proposal to spec-prod
