### ISSUE TITLE
CSS Validator can't parse `.dfn-panel.activated`.

### ISSUE THREAD

**Issue by mikewest** [w3c/specberus#321]
Bikeshed's definition panel CSS includes the rule `.dfn-panel.activated`. That throws the following error in the live pubrules checker:

> [generator.unrecognize] Parse Error (https://w3c.github.io/webappsec-credential-management/WD.html, line 29 in '.dfn-panel.activated')

The CSS is legal, validator or not.

**Comment by mikewest** [comment]
Oh, I see. It's not choking on the rule itself. It's choking on `calc(...)`.

I'd prefer not to add an exception for every WebAppSec spec. Think this is something y'all could either fix or globally exempt?

**Comment by deniak** [comment]
I'm not sure when `calc()` will be properly supported in the CSS validator so in the meantime, I suggest to use the exception system.

**Comment by mikewest** [comment]
This means that every bikeshed spec will need to talk to you about getting an exception before publication. That seems like a lot of overhead, both for you and for spec authors who will be confused by error messages that don't actually represent errors.

**Comment by deniak** [comment]
We can easily ignore specific types of error reported by the CSS validator (in this case `generator.unrecognize`) for *all* the specs. One drawback is it will ignore real errors as well.

**Comment by mikewest** [comment]
So far, the validator has prevented me from publishing both specs I've tried. Neither time has been due to a valid error (see https://github.com/w3c/specberus/pull/319 for the other one). In my personal set of ancedotes, this hasn't been a helpful check.

**Comment by deniak** [comment]
This issue will be fix if we resolve to skip the CSS validator *until it's updated*.

**Comment by mikewest** [comment]
Ping! I'm interested in seeing some resolution here; I have a number of specs whose /TR version I'd like to refresh. :)

**Comment by deniak** [comment]
I'm being told the CSS validator will very soon be able to handle `calc()` properly.

**Comment by plehegar** [comment]
I suggest ignoring the CSS validator for the next 10 days. If it's still giving errors away after that, we'll need to start ignoring the CSS validator altogether.

**Comment by mikewest** [comment]
@plehegar: I'm fine with that. I'd simply like to be able to submit some updates to `/TR` without landing exemptions for each spec. :) @deniak, WDYT?

**Comment by deniak** [comment]
@mikewest : I talked to @plehegar and what I meant is let's wait 10 days to see if the validator gets patched. After that, if it still fails on `calc()`, we'll disable the CSS validator for all the specs.
In the meantime, I'm happy to publish your specs on Tuesdays or Thursdays.

**Comment by plehegar** [comment]
To give more background: I've been told that the calc problem would be fix within 10 days in the css validator, so let's not try to make changes we would have to undo after in that timeframe. The truth is that we're catching more false positive errors in the css validation than real errors nowadays so the value of having the css validation step is clearly negative at the moment. If we can't change that within the 10 days, my proposal is to deactive the css validation step *entirely*.

**Comment by ylafon** [comment]
Should be fixed

**Comment by tripu** [comment]
:+1:, @ylafon!

@mikewest, [`https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fw3c.github.io%2Fwebappsec-credential-management%2FWD.html&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en`](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fw3c.github.io%2Fwebappsec-credential-management%2FWD.html&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en) is green now. Does that solve the issue?

**Comment by mikewest** [comment]
It does, thank you. :)

**Comment by mikewest** [comment]
Reopening: the CSS validator now fails on `left: calc(-1 * (3.5rem - 26px));` (and on a number of SVG attributes that I think we agreed to simply ignore for the moment?): https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fw3c.github.io%2Fwebappsec-secure-contexts%2FWD.html&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en

This is basically teaching me never to upgrade Bikeshed, which certainly shouldn't be the lesson. :)

@ylafon: Where should I be filing bugs against the validator?

**Comment by ylafon** [comment]
@mikewest [https://github.com/w3c/css-validator/issues](https://github.com/w3c/css-validator/issues) but I just fixed the calc() issue with the [latest commit](https://github.com/w3c/css-validator/commit/4aa879dd7ef35beb08b075610d5295993d0166b7). Thx for the report!

**Comment by ylafon** [comment]
Note that SVG properties are not part of [http://www.w3.org/TR/2015/NOTE-css-2015-20151013/](http://www.w3.org/TR/2015/NOTE-css-2015-20151013/) maybe it's a bug.

**Comment by deniak** [comment]
Closing this ticket as `calc()` is not correctly implemented in the CSS validator. The [SVG properties are not defined by the CSS WG](https://lists.w3.org/Archives/Public/www-style/2016May/0096.html). We might need to add special exceptions to ignore the errors for these properties.

**Comment by tabatkins** [comment]
The SVG properties are defined by the SVGWG; there's no requirement that all CSS must be defined by the CSSWG.  They're valid and well-defined properties, and need to be supported by the validator.  (This is currently blocking publication of Media Queries 4, will block CSS Syntax as soon as I publish that again, and will continue to block anything that uses Bikeshed's railroad-diagram support.)
