### ISSUE TITLE
Downgrade CSS Validator failures to warnings.

### ISSUE THREAD

**Issue by mikewest** [w3c/specberus#322]
In light of https://github.com/w3c/specberus/issues/321, it seems reasonable to ignore CSS Validator failures until such time as the validator validates all valid CSS. The alternative is for every bikeshed user to apply for exemptions individually, which seems like a lot of overhead.

**Comment by tripu** [comment]
(The exception can be defined for all specs, as Denis pointed out in https://github.com/w3c/specberus/issues/321#issuecomment-210341480).

**Comment by plehegar** [comment]
Given that #321 got closed and resolved, can we close this one?

**Comment by tripu** [comment]
In favour of closing, too. Waiting for @mikewest's comments.

**Comment by mikewest** [comment]
This bug was predicated upon the validator being out of date, so if y'all are confident that the validator will be doing the right thing going forward, great!

**Comment by tripu** [comment]
The CSS validator may misbehave again in the future. When that happens, and as @deniak pointed out, we can ignore that false positive for all specs at once. It is not ideal, but IMHO it's better than ignoring *all* false positives for all specs pre-emptively, as this issue seems to suggest.

**Comment by dontcallmedom** [comment]
I would like to revisit the idea of making CSS validation optional in pubrules, since there is yet another case of mis-firing errors in #500 .

While I think it's great to use valid CSS, I don't think it's a particularly important criteria for being able to publish a new draft of a spec; and given the recurrent false positives, I would suggest we leave CSS validation as a post-CR requirement (if at all).

**Comment by plehegar** [comment]
@fantasai , got an opinion?

**Comment by fantasai** [comment]
I'm OK with dom's proposal to reduce publishing friction. We should require validation for CR+ if possible, though, and provide exemptions or validator fixes as necessary. That will help to catch errors (in both the specs and the validator).

**Comment by tripu** [comment]
I don't have a strong opinion about this.

I wonder if these &ldquo;false positives&rdquo;, when they happen, have at least the benefit of pushing people into updating the checkers from time to time. That has happened a few times already.

**Comment by plehegar** [comment]
We shouldn't use pubrules as a way to force the checkers imho. +1 to downgrade css validator for <= CR

**Comment by jennyliang220** [comment]
Pubrules no longer relys on the CSS validator (#https://github.com/w3c/specberus/pull/1085). This issue duplicates https://github.com/w3c/specberus/issues/866. Pubrules currently relays on the https://validator.w3.org/nu/. 

I'm closing this issue. If there's more CSS failures in the future, let's reopen this issue and add exceptions.
