### ISSUE TITLE
False negative for document containing nav element.

### ISSUE THREAD

**Issue by skynavga** [w3c/specberus#351]
The document at [1] contains a ``nav`` element with a child ``h2`` element with text content "Table of Contents"; however, the new pubrules checker 1.5.3 reports an error:

✘ fail	headers.h2-toc	
error There is no table of contents inside a navigation element (``<nav id="toc"> … <h2>Table of Contents</h2> … </nav>``).

The document contains ``<nav id="toc"><h2 class="introductory" id="table-of-contents">Table of Contents</h2>...``. Perhaps it doesn't like the presence of ``@class`` and ``@id`` on ``h2``?

[1] https://rawgit.com/w3c/ttml2/ttml2-WD-201605XX/spec/ttml2.html

**Comment by tripu** [comment]
Thank you for reporting, @skynavga.

Specberus got confused because there are two `<h2>`s inside the `<nav id="toc">`; I submitted a fix for peer review.
