### ISSUE TITLE
Specs with Multi Entries for Latest Versions

### ISSUE THREAD

**Issue by siusin** [w3c/specberus#372]
For those specs with multi entries for the latest versions, the PubRules checkers reported errors:
"@@@No such entry: heuristic.shortname.latest-link@@@"

Check [Reporting API v1.0](https://labs.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2016%2FWD-reporting-1-20160407%2F&profile=WD-Echidna&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=true&patentPolicy=pp2004&processDocument=2015) as an example.

**Comment by deniak** [comment]
Fixed in https://github.com/w3c/specberus/commit/222d76dac4bea33749d82d77bf0528ab21b58922#diff-6cabd766ed64c85ca0bc61846c3db11e
The fix is not yet deployed but will be live at the end of this week.
