### ISSUE TITLE
Recursive validation is broken

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#391]

**Comment by tripu** [comment]
It's happening again in some cases, eg [when checking `w3.org/TR/2016/WD-html-aria-20160916`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2016%2FWD-html-aria-20160916%2F&profile=WD&validation=recursive&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004).
