### ISSUE TITLE
whacko is no longer maintained.

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#392]

**Comment by tripu** [comment]
Shall we use `cheerio` instead?

**Comment by deniak** [comment]
I think so although it would be good if they add [the support for `parse5`](https://github.com/cheeriojs/cheerio/issues/863). It's a low priority anyway

**Comment by plehegar** [comment]
jsdom is the way to go at the moment.

**Comment by tripu** [comment]
Moving this to the &ldquo;current cycle&rdquo; column; we're stuck with [this npm vulnerability](https://www.npmjs.com/advisories/577) because of this dependency.

```
$ npm ls 'lodash@<4.17.5'
specberus@3.9.2
└─┬ whacko@0.19.1
  └── lodash@3.10.1
```
