### ISSUE TITLE
The run never ends if the validators are down

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#404]

**Comment by dontcallmedom** [comment]
my suggestion is that in the connection to the validator times out, the failure should be ignored (validation is less important than prompt publication)

**Comment by deniak** [comment]
It'll easy to emit a warning if there's a timeout so it doesn't prevent a publication with Echidna but the HTML and CSS validations are a requirement for TR documents. I suppose we can let that pass for WDs but it will be more problematic the day Echidna can handle CRs, PRs and RECs

**Comment by dontcallmedom** [comment]
Yeah, failing for PR and REC might be reasonable (I would  happily ignore them  for CRs, but then I'll be called a pubrules punk).

**Comment by plehegar** [comment]
@dontcallmedom , aren't you a pubrules punk anyway?

**Comment by dontcallmedom** [comment]
@plehegar I am, but dontcalllmePubrulesPunk
