### ISSUE TITLE
"Mailing List" check doesn't account for groups using GitHub Issues

### ISSUE THREAD

**Issue by tabatkins** [w3c/specberus#408]
The CSSWG, CSS Houdini TF, and FXTF are all using GitHub Issues as their primary communication mechanism.  We're no longer recommending using www-style for general comment; it's reserved for publication announcements, pings for review, and the occasional general-interest question.

As such, the current CSSWG boilerplate omits explicit mention of sending email to www-style, and instead links to the Issues page for our repo. It does include a link to the mail archive, however.  (See the second paragraph of <https://drafts.csswg.org/css-values/#status> for an example.)

I'm currently failing Specberus due to this.  It would be nice to not have to lie about our preferred communication medium just to pass.

**Comment by plehegar** [comment]
:+1: the original goal was to ensure that all documents are clear on how to provide feedback. Ideally, we should say something like "All documents MUST provide a way to provide feedback" and not have an associated rule with it. Some documents are including since in their headers for example.

**Comment by deniak** [comment]
I agree the W3C mailing list shouldn't be a requirement as long as people can submit their comments. However, I do think there should be a rule to check that. How about we look for a specific sentence in the SotD or the headers of the document?

**Comment by plehegar** [comment]
1. remove the requirement for archive
2. add a check for GH (eg https?://github.com/.*/issues(/new)? ) and maybe others?
3. generate a warning instead of an error if no mailto: or github link

**Comment by tabatkins** [comment]
Leaving in a check for an archive sounds like a good thing, actually.  We do so, and I think it's valuable to maintain.

I'd just check for the issues page. Linking directly to the new-issue form should be fine, but not required, imo; either one should work.

**Comment by plehegar** [comment]
you mean that you'd expect the publication to fail if there is no link to the archive? That seems over constraining to me.

**Comment by tabatkins** [comment]
I think it's reasonable to require that specs link to the archive somewhere, yes; it seems similarly important to linking to the mailing list or issues page.  (In particular, it wouldn't be an impediment to my publication.)

**Comment by plehegar** [comment]
I'm not sure why we would require a link to the archive if we don't require a link to a mailing list. Or are you saying that we keep requiring a link to the mailing list even if we have a link to github?

**Comment by tabatkins** [comment]
Every group that uses GitHub issues (that I know of) archives them in a W3C list.  CSS uses public-css-archive, Houdini just uses public-houdini-archive, etc.  This is good practice because it gives a permanent record and gives us a historical record that's not dependent on GitHub's goodwill.

I recommend requiring that archive list, and linking to it from the boilerplate.  Your existing check for an archive link is perfectly adequate for that, just keep it as it is, and then change the other two checks to alternately pass if a github issues link is found.

**Comment by plehegar** [comment]
That seems indeed a good idea to me.

**Comment by tabatkins** [comment]
Cool. So let's get it in, so I can finally pass the Specberus portion and see what else I need to fix. ^_^

I can PR if you want?

**Comment by plehegar** [comment]
@deniak was looking at it before but I'm pretty confident he'd be receptive to a PR.
