### ISSUE TITLE
Validator barfs on using prefixed values followed by standardized values

### ISSUE THREAD

**Issue by tabatkins** [w3c/specberus#409]
I'm trying to publish CSS Align right now, and one of Specberus's reported failures is due to my use of some prefixed values.

Specifically, [this run](https://labs.w3.org/echidna/api/status?id=bd2349fe-f859-444e-a0c2-600255ddff4b) complains about the following:

```
        .dfn-panel {
            position: absolute;
            z-index: 35;
            height: auto;
            width: -webkit-fit-content;
            width: fit-content;
            max-width: 300px;
            max-height: 500px;
            overflow: auto;
            padding: 0.5em 0.75em;
            font: small Helvetica Neue, sans-serif, Droid Sans Fallback;
            background: #DDDDDD;
            color: black;
            border: outset 0.2em;
        }
```

Note the line `width: -webkit-fit-content;` which its angry about. This is immediately followed by the standardized name for the value in the next line, matching best practices.  This shouldn't trigger a Specberus failure.

**Comment by deniak** [comment]
Specberus relies on the [CSS validator](https://jigsaw.w3.org/css-validator/validator?uri=http%3A%2F%2Fcerberus.w3.org%2F%2Fbd2349fe-f859-444e-a0c2-600255ddff4b%2FOverview.html&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en). @ylafon is this something that can be fixed in the validator itself?

**Comment by ylafon** [comment]
fit-content is defined only in the edcopy of css3-box, not in https://www.w3.org/TR/2007/WD-css3-box-20070809/ which is the latest version published in /TR/.
Even the draft [https://drafts.csswg.org/css-box-3/ ](https://drafts.csswg.org/css-box-3/) comes with a warning saying "don't look there", so having a reference for implementation would be good (and considering the changes, it should be really fast to add.

**Comment by ylafon** [comment]
I found another reference for those values in https://www.w3.org/TR/2016/WD-css-sizing-3-20160512/#width-height-keywords so I implemented those extra values with css-sizing-3 as the reference and your example should work 
(and it means that the css3-box edcopy should be fixed somehow).

**Comment by deniak** [comment]
Thanks @ylafon

**Comment by tabatkins** [comment]
Ah, cool. I wasn't sure precisely how it counts lines; I could come up with a numbering that put the prefixed value on line 7 and that made sense to me.

Yeah, Box is a dead spec. Needs to be marked more carefully.

Thanks!
