### ISSUE TITLE
Bug in rule “sotd.group-homepage”: [Unable to find the deliverer]

### ISSUE THREAD

**Issue by svgeesus** [w3c/specberus#410]
[Unable to find the deliverer]

Found [while checking `https://www.w3.org/TR/worklets-1/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2Fworklets-1%2F&profile=FPWD&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004).

This is a joint TAG-CSS publication, which I suspect is the cause of this issue. There is a link to the CSS WG home page, but specberus does not find it.

**Comment by deniak** [comment]
Closing as it's related to #411
