### ISSUE TITLE
Bug in rules: [Required patent policy not found]

### ISSUE THREAD

**Issue by svgeesus** [w3c/specberus#411]
[Specberus does not find the patent policy paragraph, because it has been modified for a joint TAG-CSS publication.]

Found [while checking `https://www.w3.org/TR/worklets-1/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2Fworklets-1%2F&profile=FPWD&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004).

**Comment by deniak** [comment]
For joint publications, the document has to use a special wording, i.e.
```
This document was published by the <a href="homepage of the 1st WG">Working Group 1</a> and the <a href="homepage of the 2nd WG">Working Group 2</a>.
```
and
```
This document was produced by groups operating under the <a href="http://www.w3.org/Consortium/Patent-Policy-20040205/">5 February 2004 <abbr title="World Wide Web Consortium">W3C</abbr> Patent Policy</a>. <abbr title="World Wide Web Consortium">W3C</abbr> maintains a <a href="<PP link WG1>" rel="disclosure">public list of any patent disclosures  (Working Group 1)</a> and a <a href="PP link WG2" rel="disclosure">public list of any patent disclosures  (Working Group 1)</a> made in connection with the deliverables of each group; these pages also include instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains <a href="http://www.w3.org/Consortium/Patent-Policy-20040205/#def-essential">Essential Claim(s)</a> must disclose the information in accordance with <a href="http://www.w3.org/Consortium/Patent-Policy-20040205/#sec-Disclosure">section 6 of the <abbr title="World Wide Web Consortium">W3C</abbr> Patent Policy</a>.
```

For instance, see https://www.w3.org/TR/2016/WD-mediacapture-fromelement-20160607/.

That being said, the TAG is a special use case and it might not be correctly handled. I'll work on a fix.

**Comment by svgeesus** [comment]
Good that there is now standardized wording for this; in the past we had to kinda make it up on the fly for joint SVG and CSS publications).
And yes, TAG is a bit of a special case. I consulted with Ian Jacobs for suitable wording, suggest pinging him on this.
