### ISSUE TITLE
What's the actual host?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/specberus#432]
I assume it's https://www.w3.org/pubrules/api/, but can you please put that into the REST section? 

The README seems to make strange assumptions about running the thing locally?

**Comment by deniak** [comment]
You are right, I'll add a reference to the instance deployed on w3.org to the README.
However, the README is written that way because it is indeed possible to run specberus locally and use localhost.

**Comment by marcoscaceres** [comment]
I understand, but imagine most people want to use this as a NPM dependency (we made the same mistake in ReSpec 💃 ).

**Comment by deniak** [comment]
Does https://github.com/w3c/specberus/commit/cc23d94ab667c221dce46cdf19881c07740a99d7 clarify the REST API section?

**Comment by marcoscaceres** [comment]
closed via cc23d94
