### ISSUE TITLE
Squatting API_KEY

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/specberus#433]
API_KEY is pretty generic... better: 🌟W3C_API_KEY🌟

**Comment by tripu** [comment]
Really? Isn't that too long? :)

**Comment by marcoscaceres** [comment]
Nah, it's just right! Look at those stars... ok, you could omit the stars.

**Comment by tripu** [comment]
[Reviewing some long-standing issues&hellip;]

:-1: to this (to keep the environment variable name short, and to avoid breaking changes that don't seem necessary).

May I close it&hellip;?

**Comment by tripu** [comment]
Thanks, @marcoscaceres.

**Comment by tripu** [comment]
I have no preference for one name or the other, really.
I only want to have just one name, and not change it unless necessary.

I suggest we resolve this by polling users and by looking at what's the &ldquo;standard&rdquo; other public API's use for naming their keys/tokens.

GH v3, for example, uses `client_id` and `client_secret`. What do we know about others?

**Comment by marcoscaceres** [comment]
> GH v3, for example, uses client_id and client_secret. What do we know about others?

There are for HTTP API itself, right (i.e., there is no assumption about environment variables)? 

In our case, it's a little different because the code actually expects these as environment variables in order to work.
