### ISSUE TITLE
Bug in rule “sotd.group-homepage”: [group home page URL not detected]

### ISSUE THREAD

**Issue by r12a** [w3c/specberus#436]
> The homepage http://www.w3.org/International/core/ should appear in the SotD
It MUST include the name of the W3C group that produced the document. The name MUST be a link to a public page for the group.

name and link are there, but the url uses https:// rather than http:// - maybe that's significant?

Found [while checking `https://labs.w3.org/spec-generator/?type=respec&url=https://w3c.github.io/predefined-counter-styles/?specStatus=WD;shortName=predefined-counter-styles`

**Comment by deniak** [comment]
The homepages are compared against what's listed on https://www.w3.org/Member/Mail. That being said, I do think we can make the test pass if the urls match
