### ISSUE TITLE
Bug: Undefined error

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#438]
Getting unknow error `Cannot read property 'text' of undefined`

Found [while checking `https://www.w3.org/TR/2016/WD-page-visibility-2-20160623/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2016%2FWD-page-visibility-2-20160623%2F&profile=FPWD&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004).

**Comment by tripu** [comment]
Duplicate of #386.
