### ISSUE TITLE
CSS Validator barfs on SVG CSS properties

### ISSUE THREAD

**Issue by tabatkins** [w3c/specberus#451]
Trying to publish Media Queries, and getting the validator reporting that a bunch of SVG CSS properties aren't real: <https://labs.w3.org/echidna/api/status?id=8a319a87-4b26-4e66-baae-80ea1796e556>

Remind me again why CSS validation is a necessary part of the publication process? ^_^

**Comment by tabatkins** [comment]
Also the key "type" has inconsistent dashing: `noexistence-at-all`. This just bugs me. ^_^

**Comment by tabatkins** [comment]
Ping - this is blocking publication for me.

**Comment by deniak** [comment]
@tabatkins I don't know what's the plan for adding SVG properties support to the CSS validator but @ylafon [mentioned](https://github.com/w3c/specberus/issues/321#issuecomment-218083522) this might be a bug.
In the meantime, specberus allows [exceptions for specific drafts](https://github.com/w3c/specberus/blob/master/lib/exceptions.json). We could add one for the specs you need to publish.

**Comment by tabatkins** [comment]
Yes, please add one for `mediaqueries-4` so I can publish.

And this same problem will occur with any other spec that uses Bikeshed's railroad diagrams, such as CSS Syntax.  This needs to be fixed overall.

**Comment by deniak** [comment]
@tabatkins I added an exception on the CSS validator errors related to [some SVG properties](https://github.com/w3c/specberus/blob/b98f783cb6093c632df6758cd8d8b3c4c12ba782/lib/exceptions.json). This should be enough for you to publish your documents.

**Comment by deniak** [comment]
and I forgot to mention it should work for any specs, not only `mediaqueries-4`.

**Comment by tabatkins** [comment]
That worked, thanks!

**Comment by ylafon** [comment]
It should work as expected if the profile in use is "css3svg"
