### ISSUE TITLE
Bug: "Cannot read property 'text' of undefined"

### ISSUE THREAD

**Issue by shepazu** [w3c/specberus#470]
In checking Pointer Events 2 for FPWD, I got the following mysterious error: "Cannot read property 'text' of undefined". I looked for the string "text" in the document, but couldn't find anything wrong.

[EXPLANATION]

Found [while checking `https://www.w3.org/TR/2016/WD-pointerevents-20160719/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2016%2FWD-pointerevents-20160719%2F&profile=FPWD&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004).

**Comment by shepazu** [comment]
The Nu Validator does give a warning about 'role="document"' on the <body> element, but otherwise reports no errors: https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.w3.org%2FTR%2F2016%2FWD-pointerevents-20160719%2F

**Comment by deniak** [comment]
You can safely ignore that error. [The bug has been fixed](https://github.com/w3c/specberus/commit/84bb7a9871619206e023f5e065b77860c20c5415#diff-1) but not deployed yet.
