### ISSUE TITLE
Bug in rule “style.sheet”: [WHAT]

### ISSUE THREAD

**Issue by wseltzer** [w3c/specberus#476]
[EXPLANATION]

Found [while checking `https://www.w3.org/TR/2016/CR-mixed-content-20160802/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2016%2FCR-mixed-content-20160802%2F&profile=CR&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004).

**Comment by wseltzer** [comment]
I don't see any other styles there, but pubrules complains: 


    Error

    W3C TR style sheet must be last.
    Any internal style sheets MUST be cascaded before this link; i.e., the internal style sheets MUST NOT override the W3C tech report styles.

**Comment by deniak** [comment]
@wseltzer that document contains internal stylesheets (style-md-lists, style-counters, style-dfn-panel, style-selflinks, style-autolinks) declared *after* the W3C stylesheet

**Comment by wseltzer** [comment]
Thanks. For other CSS-deprived folks, a longer description of what counts as "style sheet" could help.
