### ISSUE TITLE
Bug in rule “headers.copyright”: [WHAT]

### ISSUE THREAD

**Issue by wseltzer** [w3c/specberus#496]
Copyright statement should use https for w3.org links. It currently recommends HTTP. 

[

**Comment by tripu** [comment]
@deniak fixed that in 54222d55a2430e323ed06324122a7e5682d8bb48&nbsp;, but it wasn't deployed live yet. It'll be updated in production very soon.

**Comment by tripu** [comment]
Change deployed.
