### ISSUE TITLE
Wrong metadata extracted from a WG Note

### ISSUE THREAD

**Issue by tripu** [w3c/specberus#497]
In particular, [metadata extracted from `https://www.w3.org/TR/2016/NOTE-eme-stream-webm-20160907/`](https://www.w3.org/pubrules/api/metadata?url=https://www.w3.org/TR/2016/NOTE-eme-stream-webm-20160907/) returns:
- `rectrack: true`
- `informative: false`

It should be the other way around.

This probably explains why [`https://www.w3.org/TR/2016/NOTE-eme-stream-webm-20160907/`](https://www.w3.org/TR/2016/NOTE-eme-stream-webm-20160907/) was published in spite of having the wrong patent policy paragraph.

h/t @caribouW3.

**Comment by tripu** [comment]
@deniak, I assumed that all WG notes would be *informative* and not in *rectrack*, but it seems I was wrong. We check those in [`lib/rules/metadata/informative.js`](https://github.com/w3c/specberus/blob/master/lib/rules/metadata/informative.js) and [`lib/rules/metadata/rectrack.js`](https://github.com/w3c/specberus/blob/master/lib/rules/metadata/rectrack.js) in any case.

Is the PP paragraph in [`https://www.w3.org/TR/2016/NOTE-eme-stream-webm-20160907/`](https://www.w3.org/TR/2016/NOTE-eme-stream-webm-20160907/) right, then? It seems so, looking at [`https://www.w3.org/pubrules/doc/rules/?profile=WG-NOTE#patPolReq`](https://www.w3.org/pubrules/doc/rules/?profile=WG-NOTE#patPolReq).

**Comment by caribouW3** [comment]
There are 2 ways for a spec to end up published as WG note: either it's informative and not on Rec Track from its start, or it was a spec on Rec Track and normative, but for some reason the work is stopped and the result becomes non-normative and out of Rec Track. We distinguish those 2 cases.[Note that a spec that is on Rec track and necessarily has one Ref Draft or FPWD in its history, I'm not sure Echidna has a check for that, but it should probably].

**Comment by tripu** [comment]
> There are 2 ways for a spec to end up published as WG note: either it's informative and not on Rec Track from its start, or it was a spec on Rec Track and normative, but for some reason the work is stopped and the result becomes non-normative and out of Rec Track.

Mmh, OK. But regardless of the path it took, once it's going to be published as a note, it *has* to be *recTrack=false* and *informative=true*, am I right?

**Comment by caribouW3** [comment]
Yes, I think so. In addition, there's nothing in the document that gives a hint on whether it was previously on rec track or not. You need the previous publication to be able to distinguish those cases (that's echidna's business, not specberus).

**Comment by tripu** [comment]
OK, so this bug still holds: a document successfully identified as a WG Note by Specberus should be considered *recTrack=false* and *informative=true* by the metadata extraction, or else fail.

**Comment by caribouW3** [comment]
And Patent Policy text must include the sentence "this specification is not intended to become a Recommendation" (exact wording to be checked).

**Comment by tripu** [comment]
So, if I understand correctly:

* We have to adjust the expected wording in [`lib/rules/metadata/rectrack.js`](https://github.com/w3c/specberus/blob/master/lib/rules/metadata/rectrack.js#L10) and in [`lib/rules/metadata/informative.js`](https://github.com/w3c/specberus/blob/master/lib/rules/metadata/informative.js#L10).
* Once metadata extraction has finished, there are some checks to do before we continue. For example, if `profile=WG-NOTE` but `rectrack=true`, we should throw an error.

Is that right?

What would be the right wording for those chunks of text? I can't find them [in the new pubrules](https://www.w3.org/pubrules/doc/rules/?profile=WG-NOTE) nor [in the old one](https://www.w3.org/2005/07/pubrules?year=2016&uimode=filter&filter=Filter+pubrules&filterValues=form&docstatus=wg-note-tr&patpol=w3c&normative=no&rectrack=no&procrev=2015&prevrec=none).

**Comment by tripu** [comment]
@deniak, testing this again, it seems it's fixed now.
