### ISSUE TITLE
Bug in rule “headers.dl”: Bad message for This Version syntax

### ISSUE THREAD

**Issue by jyasskin** [w3c/specberus#498]
It says "Wrong syntax for This Version link. Use a 'https' link.", but https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/w3c/permissions/01df4eaa22343b50c9ee8a38653d17f982cea659/index.bs has a "This version" link of https://w3c.github.io/permissions/, which *does* start with 'https'.

Found [while checking `https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/w3c/permissions/01df4eaa22343b50c9ee8a38653d17f982cea659/index.bs`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fapi.csswg.org%2Fbikeshed%2F%3Furl%3Dhttps%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fpermissions%2F01df4eaa22343b50c9ee8a38653d17f982cea659%2Findex.bs&profile=WD-Echidna&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=true&patentPolicy=pp2004).

**Comment by tripu** [comment]
You are right: the message is misleading. It should say something along the lines of

> &ldquo;Wrong &lsquo;this version&rsquo; link; the URL should begin with `https://www.w3.org/TR/`.&rdquo;

A link outside &ldquo;W3C TR space&rdquo; is not valid (here's [the code](https://github.com/w3c/specberus/blob/master/lib/rules/headers/dl.js#L68-L92), if you're curious).

I think this has to do with a bigger problem: the document isn't recognised as any of the valid types. You tried to validate as a working draft, but it's an &ldquo;editor's draft&rdquo;. Try to validate again, this time selecting the special profile &ldquo;auto-detect&rdquo;, and you will see that Specberus doesn't recognise the profile.

If it's a WD, at the very least [the string &ldquo;Working Draft&rdquo;](https://github.com/w3c/specberus/blob/master/public/data/profiles.json#L4) should appear [inside `$('body div.head h2')`](https://github.com/w3c/specberus/blob/master/lib/rules/metadata/profile.js#L6) (see [the rule](https://www.w3.org/pubrules/doc/rules/?profile=WD#dateTitleH2)).
