### ISSUE TITLE
Bug in rule “headers.dl”: When shortnames differ, say what they are

### ISSUE THREAD

**Issue by jyasskin** [w3c/specberus#499]
Given an error like "Shortnames differ between This and Latest Versions.", it's hard to tell where it's pulling the shortname from. If you said "This Version's shortname is 'foo', but Latest Version's shortname is 'bar'", it'd be easier to find what to fix.

Found [while checking `https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/w3c/permissions/01df4eaa22343b50c9ee8a38653d17f982cea659/index.bs&md-status=WD`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fapi.csswg.org%2Fbikeshed%2F%3Furl%3Dhttps%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fpermissions%2F01df4eaa22343b50c9ee8a38653d17f982cea659%2Findex.bs%26md-status%3DWD&profile=WD-Echidna&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=true&patentPolicy=pp2004).

**Comment by deniak** [comment]
Fixed in https://github.com/w3c/specberus/pull/1067
