### ISSUE TITLE
Bug in rule “validation.css”: FILL colors rejected

### ISSUE THREAD

**Issue by wseltzer** [w3c/specberus#500]
as far as I can tell,      fill: #FF0000; is legitimate, yet it's rejected, along with some other hex colors.

Found [while checking `https://www.w3.org/TR/2016/CR-secure-contexts-20160915/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2016%2FCR-secure-contexts-20160915%2F&profile=CR&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004).

**Comment by tripu** [comment]
Yes, I don't see the problem with
```css
.secure {
    fill: #88FF88;
}
```
either&hellip;

In any case, I think this is [a question for the CSS validator](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fwww.w3.org%2FTR%2F2016%2FCR-secure-contexts-20160915%2F&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en), not for Specberus. So, unless someone comments here, I'll file an issue there.

**Comment by tripu** [comment]
See w3c/css-validator#59.
