### ISSUE TITLE
[Under assessment] Delete rule requiring link to translations page?

### ISSUE THREAD

**Issue by tripu** [w3c/specberus#552]
eg, [`w3.org/pubrules/doc/rules/?profile=REC#translation`](https://www.w3.org/pubrules/doc/rules/?profile=REC#translation)

**Comment by koalie** [comment]
FWIW, I support deleting the rule requiring link to translations page, and by the same token, removing the following from our Specs template: "Non-normative <a href="https://www.w3.org/Consortium/Translation/">translations</a> may also be available."

**Comment by tripu** [comment]
What template do you mean, @koalie? ReSpec/Bikeshed?

**Comment by koalie** [comment]
I have no idea. But in my badly informed conception, there is pubrules (a checker) on one hand, and there's some tool that the editors use to generate the specs. 

It's that tool I have in mind, that needs to stop inserting the snippet "Non-normative <a href="https://www.w3.org/Consortium/Translation/">translations</a> may also be available."

**Comment by tripu** [comment]
[ReSpec](https://github.com/w3c/respec/blob/cd363b9ccee3251e6e32895b702f3f5b34855238/js/w3c/templates/headers.html#L124-L127) (and perhaps Bikeshed), then.

**Comment by koalie** [comment]
I just had to "thumb down" my 7-Dec comment, as I don't know how to comment on it directly and I don't want to delete it.
In the meantime, expectations are shifting as to translations.
I'd like to understand what our options are (short/long term) before I can weigh in on #570 and #552.

**Comment by plehegar** [comment]
what's the update on this front? Did we drop the requirement?

**Comment by koalie** [comment]
There was push-back (from AB and then W3M was sympathetic) to removing from specs "Non-normative translations may also be available." as it would weaken our positioning as a global and inclusive SDO. This and #570 are on hold until we can figure out a way to make non-normative translations available.

**Comment by tripu** [comment]
(Roger that. On hold it stays, then.)
