### ISSUE TITLE
Bug in rules: Errata-paragraph-checking over-strict?

### ISSUE THREAD

**Issue by wseltzer** [w3c/specberus#556]
[EXPLANATION]

Found [while checking `https://www.w3.org/TR/2016/REC-CSP2-20161215/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2016%2FREC-CSP2-20161215%2F&profile=REC&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004).

**Comment by tripu** [comment]
Here is [the current rule](https://www.w3.org/pubrules/doc/rules/?profile=REC#errata).

How do you suggest we check that instead, @wseltzer? Adding alternative wording that is specific for groups using GH issues for that?

**Comment by wseltzer** [comment]
@tripu checking for the word errata, hyperlinked, would be enough for me. (I borrowed the usage of the github link from the html5.1 spec.)

**Comment by tripu** [comment]
No objection from me. Let's hear from others.

**Comment by deniak** [comment]
The [original rule (section "Errata Information")](https://www.w3.org/2005/07/pubrules?year=2016&uimode=filter&filter=Filter+pubrules&filterValues=form&docstatus=rec-tr&patpol=w3c&rectrack=yes&normative=yes&procrev=2005&prevrec=none#docreqs) requires a `<strong>` element inside an `<a>` for the errata. I'm not sure what are the motivations behind using that element. Maybe @ianbjacobs knows more.
In any case, I'm open to relaxing that rule a little bit. Pinging @plehegar too.

**Comment by plehegar** [comment]
SGTM
