### ISSUE TITLE
Process 2017

### ISSUE THREAD

**Issue by plehegar** [w3c/specberus#565]
Starting March 1st, 2017, the W3C will switch to a new W3C Process. We should allow it the use of the new Process starting on that date, and issue a warning if it still uses Process 2015.
Starting April 1st, 2017, we should no longer accept Process 2015 in documents.

**Comment by deniak** [comment]
@plehegar, ok with the 1-month transition period.
Apart from that and https://github.com/w3c/specberus/issues/483, do you see other updates to specberus?

**Comment by tripu** [comment]
Closed by #572.
