### ISSUE TITLE
Bug in rules: Recommendation for "back to top" link is incorrect

### ISSUE THREAD

**Issue by michaelhkay** [w3c/specberus#569]
[EXPLANATION]

Found [while checking `http://www.w3.org/XML/Group/qtspecs/specifications/xslt-30/html/Overview.html`](https://www.w3.org/pubrules/?url=http%3A%2F%2Fwww.w3.org%2FXML%2FGroup%2Fqtspecs%2Fspecifications%2Fxslt-30%2Fhtml%2FOverview.html&profile=CR&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004).

The pubrules checker recommends including a back-to-top link at the end of the body with a target of "#toc". But this doesn't work with the TOC in a separate panel; the target should probably be "#title".

**Comment by tripu** [comment]
@michaelhkay, why do you say it doesn't work? It seems to work well in that spec, [`w3.org/XML/Group/qtspecs/specifications/xslt-30/html/Overview.html`](https://www.w3.org/XML/Group/qtspecs/specifications/xslt-30/html/Overview.html). What is the issue?
