### ISSUE TITLE
Retire Process 2015

### ISSUE THREAD

**Issue by plehegar** [w3c/specberus#582]
Modify the changes in https://github.com/w3c/specberus/commit/5bc2b6b96d959249ff2b544c107a9bdd90674098 to return an error if Process 2015 is used (to be deployed in April 2017)

**Comment by deniak** [comment]
That's already the case (see https://github.com/w3c/specberus/commit/cafd228d48a1626a3a759587a15329a54ea43e07). After the transition period, [the old process will trigger an error](https://github.com/w3c/specberus/blob/master/lib/rules/sotd/process-document.js#L46).
