### ISSUE TITLE
Bug: Forbidden

### ISSUE THREAD

**Issue by svgeesus** [w3c/specberus#619]
Doing a pubrules check on an updated CR for manual publication, I got one error:

`
    Bug Forbidden
`

Found [while checking `https://www.w3.org/TR/2017/CR-css-grid-1-20170502/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2017%2FCR-css-grid-1-20170502%2F&profile=CR&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004).

**Comment by tripu** [comment]
@svgeesus, I can't reproduce this error. Can you?
