### ISSUE TITLE
PER isn't a thing anymore

### ISSUE THREAD

**Issue by plehegar** [w3c/specberus#628]
https://www.w3.org/2017/Process-20170301/ actually removed the concept of Proposed Edited Recommendation. 
Compare https://www.w3.org/2015/Process-20150901/#revised-rec with https://www.w3.org/2017/Process-20170301/#revised-rec .

If Editorial changes -> REC
If Substantive changes -> CR

@chaals in case he'd like to disagree

**Comment by chaals** [comment]
> To make corrections to a Recommendation that produce substantive changes but do not add new features, or where there were votes against publishing the corrections directly as a Recommendation, a Working Group may request publication of a Candidate Recommendation, without passing through earlier maturity levels.

> In the latter two cases, the resulting Recommendation is called an Edited Recommendation.

Prior to being an Edited Recommendation it  has to be a Candidate Recommendation. And all Candidate Recommendations that want to become Recommendations have to be Proposed Recommendations in the middle...

The impact here is unclear to me, so maybe that's just repeating what you said...

**Comment by plehegar** [comment]
@chaals we agree indeed for substantive changes indeed.
