### ISSUE TITLE
Don't require mailing list

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/specberus#629]
When [trying to publish](https://lists.w3.org/Archives/Public/public-tr-notifications/2017May/0075.html), I'm hitting:

```JS
      "specberus": {
        "status": "failure",
        "errors": [
          {
            "key": "no-arch",
            "type": {
              "name": "sotd.mailing-list"
            }
          }
        ]
      },
```

However, we are not using a mailing list for our spec feedback (nor do we want to use it for CR). This requirement should be relaxed.

**Comment by marcoscaceres** [comment]
(we are naturally using github instead)

**Comment by tripu** [comment]
@deniak, @plehegar: shall we relax the &ldquo;mailing list&rdquo; rules ([#mailingListName](https://www.w3.org/pubrules/doc/rules/?profile=WD#mailingListName), [#mailingListLink](https://www.w3.org/pubrules/doc/rules/?profile=WD#mailingListLink)) to accomodate GitHub popularity&nbsp;&mdash;&nbsp;like we did with the &ldquo;errata&rdquo; rule (#556 #609) already?

**Comment by marcoscaceres** [comment]
<img width="502" alt="screenshot 2017-05-17 18 41 03" src="https://cloud.githubusercontent.com/assets/870154/26145618/693c293c-3b30-11e7-96af-c27dae0168ce.png">

**Comment by plehegar** [comment]
yes. I thought we had relax it already. In fact, we may end requiring GitHub issues for tracking bugs on our specifications in the future.

**Comment by plehegar** [comment]
Just to be clear: the cat picture helped a lot in making the argument here. Who would force such cat to use a mailing list? :)

**Comment by marcoscaceres** [comment]
> Who would force such cat to use a mailing list? 

I know, right!?! 😸

Let me know if there is anything I can do to help move this along. I've got a few specs that omit mailing lists. I think @chaals also has one ore more, as he was the one that added the feature to ReSpec.

**Comment by chaals** [comment]
I'd like to get it out of a lot of specs…

**Comment by plehegar** [comment]
@deniak will fix it by Monday

**Comment by plehegar** [comment]
Actually, we ought to *require* a GitHub repository if the publication is a Recommendation (to align with the maintenance discussion).

**Comment by marcoscaceres** [comment]
Yay! Could you kindly please also notify the spec-prod mailing list (heh, the irony!) of the change once it ships.

**Comment by tripu** [comment]
I will, @marcoscaceres.

**Comment by sandhawke** [comment]
-1   Formal Objection to requiring W3C specification use github.  Do I really need to explain this?

**Comment by plehegar** [comment]
I'm sorry, but allowing specs to use whatever they want to track issues beyond Recommendations and expecting W3C to keep on top of all of those systems for years isn't reasonable imho. GitHub is a system that allows to build on top very easily.

**Comment by sandhawke** [comment]
To illustrate my point: will the next step be requiring working group meetings be scribed on Facebook?

You might reply, "Of course not, but Slack might be good."   And I'll say now [we're just haggling over the price](http://quoteinvestigator.com/2012/03/07/haggling/).

**Comment by sandhawke** [comment]
(Tantek tells me he's raised this with AB.)

**Comment by tantek** [comment]
Yes I did, at the most recent meeting https://www.w3.org/wiki/AB/2017-06-MA, in which I said something like https://chat.indieweb.org/social/2017-07-19/1500485686239000

**Comment by chaals** [comment]
This is a longstanding issue - there have been discussions about, for example, accessibility of tools - it turns out that different people have different needs and different tools meet them or fail to do so - and availability of tools, for example because some tools used by groups are commonly blocked by firewalls - meaning that using some tools on a work computer, and/or for work, is difficult or impossible creating a real barrier.

One of the goals of the tooling project the AB took on a while ago is to work out what tools people are relying on - and whether they are maintained. My personal perception is that W3C doesn't yet know what tools it needs, nor even what tools it uses, which makes it hard to make rational well-informed statements about what it can or should maintain.

**Comment by tripu** [comment]
@marcoscaceres said:

> *&ldquo;Yay! Could you kindly please also notify the spec-prod mailing list (heh, the irony!) of the change once it ships.&rdquo;*

[We did that](https://lists.w3.org/Archives/Public/spec-prod/2017JulSep/0000.html), so closing this issue now.

The general discussion about GitHub and other tools, and about what should be supported, encouraged or required, should happen elsewhere, IMHO (the AB, [`w3c/modern-tooling`](https://github.com/w3c/modern-tooling), [`w3c/w3c.github.io`](https://github.com/w3c/w3c.github.io), etc).
