### ISSUE TITLE
Transitions docs will be on github

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#637]
Update the links to the transition steps once https://w3c.github.io/transitions/ becomes official

**Comment by fantasai** [comment]
I don't really think we should be hosting anything on GitHub unless we *want* it to be a temporary URL that may someday disappear when we no longer use GitHub.

**Comment by deniak** [comment]
Thanks for reviving that old issue. Yes, the official should be https://www.w3.org/Guide/transitions which is already the case today. The issue can be closed.
