### ISSUE TITLE
Previous version link for FPWD

### ISSUE THREAD

**Issue by svgeesus** [w3c/specberus#642]
Pubrules says [1] not to have a Previous Version link for FPWD.

Often, specifications have versions or levels, so it is common to have a FPWD of version n which could usefully point to a more mature spec of version n-1.
Is [1] still good advice? In general we seem to be moving stuff from SOTD (where it is never read) to headers.

[1] https://www.w3.org/pubrules/doc/rules/?profile=FPWD#docIDOrder

**Comment by tripu** [comment]
(@plehegar or @deniak probably have an answer to this.)

**Comment by deniak** [comment]
I think that rule still applies. It's possible to split a specification though but that means you don't publish a FPWD. It also affects IPP which follows the history of the spec trying to find the last CfE, etc.
Basically, I don't think what we call FPWD in /TR can have a previous version.

**Comment by svgeesus** [comment]
@deniak 
> I don't think what we call FPWD in /TR can have a previous version.

I think that every CSSWG FPWD at level 3 or above, which is not a delta specification, has a previous version. And this has an impact on IPP; people can't exclude on stuff that was already in a previous level.

**Comment by plehegar** [comment]
see also https://github.com/w3c/tr-pages/issues/16

**Comment by jennyliang220** [comment]
`Previous Versions` is a keyword for publication tools, and the links are used for some calculation. If you want to keep previous TR link in the header, please change the <dt> title from 'Previous Versions:’ to ‘Previous Recommendations’ or ‘Previous Levels’, anything without keyword ‘Previous Versions’ will do.

A good example would be: https://www.w3.org/TR/2021/WD-webauthn-3-20210427/, which use `Previous Recommendations` wording.
