### ISSUE TITLE
Respec permalinks break pubrules

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#673]
Respec can now add permalinks to the generated documents:
https://github.com/w3c/respec/wiki/includePermalinks

This breaks pubrules as it's adding unexpected markups.

**Comment by plehegar** [comment]
in the meantime, one should use: "includePermalinks: false" in the respecConfig to deactivate those permalinks and avoid confusing pubrules.

**Comment by sidvishnoi** [comment]
Not sure if it's relevant anymore, but the config option is now called [`addSectionLinks`](https://respec.org/docs/#addSectionLinks).

**Comment by jennyliang220** [comment]
Respec document sample:
## With addSectionLinks
- respec: https://w3c.github.io/pwpub/?addSectionLinks=true
- spec-generator result: https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fw3c.github.io%2Fpwpub%2F%3FaddSectionLinks%3Dtrue&file=
- pubrules result (doesn't break): https://www.w3.org/pubrules/?url=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%3A%2F%2Fw3c.github.io%2Fpwpub%2F%3FaddSectionLinks%3Dtrue%26file%3D&profile=WG-NOTE&validation=simple-validation&noRecTrack=true&informativeOnly=true&echidnaReady=false&patentPolicy=pp2020

## without addSectionLinks
- respec: https://w3c.github.io/pwpub/?addSectionLinks=false

**Comment by jennyliang220** [comment]
Specberus won't break anymore.
