### ISSUE TITLE
Bug in rules: meta tag requires, though it is there...

### ISSUE THREAD

**Issue by iherman** [w3c/specberus#678]
[EXPLANATION]

Found [while checking `https://www.w3.org/TR/2017/CR-odrl-model-20170926/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2017%2FCR-odrl-model-20170926%2F&profile=CR&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004) an error message on the missing <meta> element for viewport, although the entry _is_ in the source...

**Comment by tripu** [comment]
That document has two instances of `<meta name="viewport" ⋯ />`, with slightly different `content`s.

Pubrules expects to find exacly one.

(Both [the rule](https://www.w3.org/pubrules/doc/rules/?profile=CR#viewport) and the error message shown when checking the spec specify that `content` should be `width=device-width, initial-scale=1, shrink-to-fit=no`.)

**Comment by iherman** [comment]
Ouch. I see now the problem. Respec generated a meta element into the document, but it is not o.k. per pubrules (it does not include `shrink-to-fit=no`), and I did not realize this and added the required meta element verbatim. Ie, this is a respec problem...
