### ISSUE TITLE
There is a new dated version to the Patent Policy

### ISSUE THREAD

**Issue by plehegar** [w3c/specberus#696]
Doh! We switched to https://www.w3.org/Consortium/Patent-Policy-20170801/  and didn't update our tooling...

Needs coordination with @tabatkins and @marcoscaceres

**Comment by tabatkins** [comment]
So what needs changing?

**Comment by plehegar** [comment]
The change should be simple: replacing https://www.w3.org/Consortium/Patent-Policy-20040205/ with https://www.w3.org/Consortium/Patent-Policy-20170801/ . The date doesn't change.

But you shouldn't do anything until the pubrules checker gets update first, otherwise you'll get all of your automatic publications to fail. It may be that we need to get the pubrules to accept both for a short period to avoid messing up the publications. I'll let Denis decide on to change this without causing headaches. It's likely that we can send pull requests for respect and bikeshed.

**Comment by marcoscaceres** [comment]
Ok, will wait for a PR... I guess the file that needs updating is "js/w3c/templates/sotd.html".

**Comment by deniak** [comment]
@marcoscaceres @tabatkins, here's the markup that will become mandatory starting from Dec 1:
```html
<p>
This document was produced by a group operating under the <a href="https://www.w3.org/Consortium/Patent-Policy/"> <abbr title="World Wide Web Consortium">W3C</abbr> Patent Policy</a>. <abbr title="World Wide Web Consortium">W3C</abbr> maintains a <a href="https://www.w3.org/2004/01/pp-impl/40318/status" rel="disclosure">public list of
any patent disclosures</a> made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains <a href="https://www.w3.org/Consortium/Patent-Policy/#def-essential">Essential Claim(s)</a> must disclose the information in accordance with <a href="https://www.w3.org/Consortium/Patent-Policy/#sec-Disclosure">section 6 of the <abbr title="World Wide Web Consortium">W3C</abbr> Patent Policy</a>.
</p>
```

We will allow both the former and the new markups until that date.
