### ISSUE TITLE
Add an option to return the actual error values

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/specberus#706]
Right now, the returned errors, etc. are just ids (e.g., "links.linkchecker"). It would be nice to either return the actual error description, or have an API to look up a batch of error ids to get back the english text.

**Comment by tripu** [comment]
(In the meantime, the &ldquo;manual lookup API&rdquo; goes more or less like this: ➀ open [`lib/l10n-en_GB.js`](https://github.com/w3c/specberus/blob/master/lib/l10n-en_GB.js); ➁ press `⎈`+`F`; ➂ enter the error ID, eg `links.linkchecker` and find the human-readable message.)

**Comment by binji** [comment]
It would be nice to have the additional information for validators too; this is what I get currently:
```
...
{"name":"validation.css","section":"document-body","rule":"cssValide"},
{"name":"validation.html","section":"format","rule":"valideHTML"},
{"name":"validation.html","section":"format","rule":"valideHTML"},
{"name":"validation.html","section":"format","rule":"valideHTML"},
{"name":"validation.html","section":"format","rule":"valideHTML"},
{"name":"validation.html","section":"format","rule":"valideHTML"},
{"name":"validation.html","section":"format","rule":"valideHTML"},
...
```

I ended up hacking `rule/validation/html.js`. to log the full errors, e.g.

```
{ line: 4983,
  column: 2839,
  message: 'Duplicate attribute “style”.',
  link: 'https://validator.w3.org/nu/?doc=null' }
```

**Comment by sidvishnoi** [comment]
To get proper message from API results, we need access to `key`.

Looking at the code, I think it's a bug that `key` and `extra` info are not available.
https://github.com/w3c/specberus/blob/6321df0ce152d7d56357d39f7f8253a256a91b0b/lib/validator.js#L149
https://github.com/w3c/specberus/blob/6321df0ce152d7d56357d39f7f8253a256a91b0b/lib/validator.js#L106

It should probably be something like:
```
 self.sink.on('err', function (...data) { errors.push(data); }); 
```
...but probably flattened into a single object.

Was trying to integrate this with ReSpec today.
