### ISSUE TITLE
Guidance for Member Submissions blank

### ISSUE THREAD

**Issue by wseltzer** [w3c/specberus#714]
https://www.w3.org/pubrules/doc/rules/?profile=MEM-SUBM is blank

When I look for guidance about a Member Submission in pubrules,
the page is blank. Is there someplace else we're keeping the
documentation of pubrules requirements for those? (or a bug preventing
them from displaying)

I had previously used the link
<http://www.w3.org/2005/07/pubrules?year=2015&uimode=filter&filter=Filter+pubrules&filterValues=form&docstatus=mem-subm&patpol=w3c&rectrack=yes&normative=yes&procrev=2005&prevrec=none#docreqs>

**Comment by plehegar** [comment]
This is a duplicate of https://github.com/w3c/specberus/issues/397

See also 
 https://github.com/w3c/specberus/issues/366
