### ISSUE TITLE
Bug in rules: [translation link]

### ISSUE THREAD

**Issue by svgeesus** [w3c/specberus#730]
**Warning:**
"The recommended link is not used (http[s]://[www.]w3.org/2003/03/Translations/byTechnology?technology=[shortname])"

But it is:

&lt;p>See also &lt;a href="http://www.w3.org/2003/03/Translations/byTechnology?technology=WOFF2"> &lt;strong>translations&lt;/strong>&lt;/a>.&lt;/p>

Found [while checking `https://www.w3.org/TR/2018/REC-WOFF2-20180220/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2018%2FREC-WOFF2-20180220%2F&profile=REC&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004).

**Comment by tripu** [comment]
@svgeesus, I'm afraid there's an error in the *description* of the rule: HTTPS is required (HTTP is not accepted).

I was going to fix this, but it's likely that the rule about translations is going to be dropped very soon (cf #570), so perhaps not worth it.

In the meantime, what you can do to get rid of that warning is link to link to `https://www.w3.org/2003/03/Translations/byTechnology?technology=WOFF2` instead.
