### ISSUE TITLE
Bug in rule “echidna.editor-ids”: Undefined what's required?

### ISSUE THREAD

**Issue by gsnedders** [w3c/specberus#749]
Found [while checking `https://drafts.csswg.org/css2/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fdrafts.csswg.org%2Fcss2%2F&profile=WD-Echidna&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=true&patentPolicy=pp2004).

The error here is:

> Editor IDs must be set for each editor, in the data-editor-id attribute.

The quoted pubrules is:

> § The editors'/authors' names must be listed. Affiliations and email addresses are optional; email addresses are not recommended. If an editor/author is acknowledged in an earlier version of this document and the individual's affiliation has since changed, list the individual using the notation "<name>, <affiliation> (until DD Month YYYY)". If the list of authors is very long (e.g., the entire Working Group), identify the authors in the acknowledgments section, linked from the head of the document. Distinguish any contributors from authors in the acknowledgments section.

What's the `data-editor-id` attribute? The quoted pubrules doesn't mention it at all, and https://www.w3.org/pubrules/doc/rules doesn't even contain any mention of `data-editor-id`, yet alone say anything about what its value should be.

**Comment by deniak** [comment]
@gsnedders, first sorry for the late reply. I completely missed that one.

The `data-editor`id` is only required when you try to publish with Echidna (which is the case from the url you gave). It's documented in [Echidna's wiki](https://github.com/w3c/echidna/wiki/Preparing-your-document#data-editor-id) but I reckon there should be a link in pubrules' documentation as well. I'll submit a fix.

**Comment by gsnedders** [comment]
Oh, I can't read. :) (I probably enabled it for some reason I've now forgotten.)

**Comment by tripu** [comment]
(Part of a general issue about documentation.)
