### ISSUE TITLE
Don't request "mailing list" (ie, GH issues) in SotD if "file a bug" link found already at the beginning?

### ISSUE THREAD

**Issue by tripu** [w3c/specberus#756]
@sideshowbarker just saw [Pubrules validation](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2018%2FREC-webdriver1-20180605%2F&profile=REC&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004) for [`w3.org/TR/2018/REC-webdriver1-20180605/`](https://www.w3.org/TR/2018/REC-webdriver1-20180605/) fail; he thought the inclusion of the [&ldquo;file a bug&rdquo;](https://github.com/w3c/webdriver/issues/) link at the beginning would suffice (and he has a point).

Now that the &ldquo;mailing list&rdquo; is always a link to GH issues, can we make do without the redundancy? Can we not demand that the link is present in the SotD if it's already in the *front matter* section?

@deniak, @plehegar?

**Comment by plehegar** [comment]
we don't detect the inclusion of "file a bug" at the moment. I see that respec and bikeshed are doing differently. Respec uses "file a bug" under the header "Participate" and bikeshed doesn't have a "file a bug". Personnally, I prefer the Respec approach here. We could implement the detection based on the Respec and skip the rule is found.

**Comment by plehegar** [comment]
(this is relevant for @tabatkins and @marcoscaceres )

**Comment by deniak** [comment]
If we hide the headers by default as shown in @plehegar's [proposal](https://rawgit.com/w3c/tr-design/versioning/versions-proposal.html), I think we should keep the requirement in the SotD so it's easier to find.

**Comment by deniak** [comment]
closing as it's been fixed with the changes we made for process 2020
