### ISSUE TITLE
Can't get info on fails for Note

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/specberus#768]
_From @michael-n-cooper on July 24, 2018 17:3_

I'm preparing to publish a WG NOTE and running the following check through Echidna: https://www.w3.org/pubrules/?url=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%3A%2F%2Frawgit.com%2Fw3c%2Faria-practices%2FJuly_2018_Note%2Faria-practices.html&profile=WG-NOTE-Echidna&validation=simple-validation&noRecTrack=true&informativeOnly=false&echidnaReady=true&patentPolicy=pp2004

It returns an error "Required patent policy paragraph not found." But as far as I can tell, the patent policy paragraph is there and presumed correct as generated by Respec. Attempting to look at the list of rules to see specifically what Echinda is looking for that isn't there via https://www.w3.org/pubrules/doc/rules?profile=WG-NOTE-Echidna, it simply says "Error: unknown profile WG-NOTE-Echidna". Therefore I am unable to determine why Echidna is failing this check.

_Copied from original issue: w3c/echidna#591_

**Comment by deniak** [comment]
I believe that issue is not fixed as pubrules now shows the expected patent policy paragraph when there's an error. We'll reopen if necessary
