### ISSUE TITLE
Requiring GitHub issues for all drafts

### ISSUE THREAD

**Issue by plehegar** [w3c/specberus#775]
At the moment, we only require this at REC time. It's time to require it systematically...

@tabatkins @marcoscaceres, do you folks concur?

cc @swickr

**Comment by marcoscaceres** [comment]
SGTM.

**Comment by tabatkins** [comment]
yes

**Comment by jennyliang220** [comment]
Currently specberus is checking mailing-list (GH issues also in this rule) rule for all TR docs:
https://github.com/w3c/specberus/blob/d3e3921f01a44628cf1d00b08e672e12c4a147c6/lib/profiles/TR.js#L8

But the rule only display error for REC when no GH issue link is found.
For other types of spec like `PR` or `WG-NOTE`, it allows `mail list` and `mailing archives` as an alternative for GH issue.
https://github.com/w3c/specberus/blob/d3e3921f01a44628cf1d00b08e672e12c4a147c6/lib/rules/headers/mailing-list.js#L38-L45

@plehegar , shall we change the rule:
- to require GH issues link for all types of TR docs? 
- Is mailing list and mailing archives still needed?

**Comment by plehegar** [comment]
Requiring GH issues link is a good thing. Mailing list link is optional. It provides an alternative to GH since not everyone is comfortable raising issues through GH.

**Comment by jennyliang220** [comment]
>  Mailing list link is optional. It provides an alternative to GH since not everyone is comfortable raising issues through GH.

Currently GH link is a `must` only for RECs. As for other documents, if people are not a GH user, they can also write `both mail list AND mail archive`. 

If GH link is not a `must` for other documents like PR or WG-NOTE, the rule [mailing-list](https://github.com/w3c/specberus/blob/d3e3921f01a44628cf1d00b08e672e12c4a147c6/lib/rules/headers/mailing-list.js#L38-L45) would remain unchanged. @plehegar
