### ISSUE TITLE
Integrate third-party-checker to enforce self-contained document

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#777]
Once it's done remove the checker from echidna

**Comment by jennyliang220** [comment]
Probably move `third-party-resources-checker` from echidna.

 https://github.com/w3c/echidna/blob/dec6d7d6fca09e8f07efe1f1240ee08589ee743c/package.json#L36

**Comment by jennyliang220** [comment]
We need a allowList for resources not in base folder, such as `https://www.w3.org/StyleSheets/TR/2016/base.css`. Here are all I can think of:
```
[
    'https://www.w3.org/StyleSheets/TR/2016/base.css',
    'https://www.w3.org/StyleSheets/TR/2016/W3C-CR',
    'https://www.w3.org/StyleSheets/TR/2016/logos/W3C',
    'https://www.w3.org/scripts/TR/2016/fixup.js',
    'https://www.w3.org/TR/tr-outdated-spec'
]
```
@deniak the question is, is `(https://www.w3.org/analytics/piwik/matomo.js` allowed? Are there any more allowed resources?

**Comment by jennyliang220** [comment]
When checking `https://www.w3.org/TR/2021/CR-webaudio-20210114/`, pubrules should report errors:

> This resource or link found in document (https://www.w3.org/scripts/MathJax/2.7.5/MathJax.js) is not in the same folder as the document (https://www.w3.org/TR/2021/CR-webaudio-20210114/). Please install them in the same folder.
