### ISSUE TITLE
If the document is on REC-track, make sure the WG is chartered to produce REC-track documents

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#782]

**Comment by tripu** [comment]
Using the W3C API.

**Comment by jennyliang220** [comment]
@deniak is this still necessary? The [charter 9-PP](https://www.w3.org/2021/01/miniapps-wg-charter.html) does mention 
> W3C seeks to issue Recommendations that can be implemented.

But there's no such data in https://api.w3.org/groups/@@/charters API. If we're adding the check, the API needs to be added first.

**Comment by deniak** [comment]
That issue can be closed. The charter check was added last year.

**Comment by deniak** [comment]
Discussing with @jennyliang220, I'm re-opening that issue as we don't check if a group is operating under a current charter for FPWD, WD, CRS, CRD, PR, REC, WG-NOTE.
The check is pretty similar to what we are doing in https://github.com/w3c/specberus/blob/main/lib/rules/sotd/charter-disclosure.js except that we don't look for specific sentences.
