### ISSUE TITLE
Make API key an option 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/specberus#783]
For the API_KEY, it would be great if it could be passed as an option to `validate()`. In building a tool, I want to be able to do:

```
npx respec-validator --w3c-api-key=the-key --other-options index.html
```

which later calls:

```JS
async function doPubRulesValidation(file, profile = "WD") {
  const Specberus = require("specberus");
  const events = new EventSink();
  Specberus.validate({ file, profile, events, /* API_KEY_HERE*/ });
  await events.done();
}
```

**Comment by jennyliang220** [comment]
Hi @marcoscaceres , is this still necessary? (The issue is 3 years old, so...)
If necessary, we can implement this.

**Comment by marcoscaceres** [comment]
Like Octokit would be great... The main thing is just being able to pass the API key somehow.
