### ISSUE TITLE
Fix automatic publishing to npm

### ISSUE THREAD

**Issue by tripu** [w3c/specberus#790]
The Travis builds for the last release, `v4.0.0`, did not manage to publish to npm (I published this one manually just now):

https://travis-ci.org/w3c/specberus/jobs/460199706
https://travis-ci.org/w3c/specberus/jobs/460199707

```
npm ERR! publish Failed PUT 401
npm ERR! code E401
npm ERR! You must be logged in to publish packages. : specberus
```

Find out why (did our password change? need to re-encodee? missing var in Travis?), and fix.

**Comment by deniak** [comment]
Old issue. Closing as I don't have any problem publishing to npm these days.
