### ISSUE TITLE
Make data-editor-id mandatory for each editor

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#793]
`data-editor-id` is currently not mandatory when listing an editor. It's an issue for Echidna as it relies on that attribute to get the editors of the specifications.
Can we make that attribute mandatory for each editor?

We need to make sure there's a `data-editor-id` for each editor (for instance: https://www.w3.org/TR/2020/WD-selection-api-20200226/)

**Comment by jennyliang220** [comment]
@plehegar we are going to implement this feature in the following days. If there's anything to change, you can comment here :)

**Comment by jennyliang220** [comment]
[This document](https://www.w3.org/TR/2020/WD-wot-architecture11-20201124/) can be used as example for missing `data-editor-id`.
