### ISSUE TITLE
Preventing use of links to legacy W3C services

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/specberus#803]
W3C Systems Team is looking at retiring the following services by April 1st, 2019:
* [W3C Bugzilla](https://www.w3.org/Bugs/Public/)
* [W3C Public CVS on dev.w3.org](https://dev.w3.org/cvsweb/)
* [W3C Mercurial on dvcs.w3.org](https://dvcs.w3.org/hg)

The data will either be migrated to a replacement service (eg GitHub) (mainly for active repositories), or archived and kept available as read-only (preserving current URIs as much as possible).

We should ensure that none of the W3C specifications either in development or that would need ongoing maintenance link to any of those services.
@plehegar was suggesting that specberus should have a check to block the use of such links in newly published documents.

Surveying current usage on W3C specs, I created an [online spreadsheet](https://docs.google.com/spreadsheets/d/146mSR28LMd73BGU6BsEr9wp8ui4oqZQo6kakWNNfovE/edit?usp=sharing) of current W3C TR documents (which excludes retired or superseded docs) and their number of occurrence of `w3.org/Bugs`, `dev.w3.org` or `dvcs.w3.org` (and as a bonus link to [W3C Tracker instances](https://www.w3.org/2005/06/tracker/) who would likely be retired in a future services cleanup iteration).

**Comment by swickr** [comment]
I don't think we should block use of links to Bugzilla (they might, for example, be useful historical references).  Specberus could, however, give warnings to alert the editors to consider whether the reference is appropriate.

**Comment by plehegar** [comment]
I deployed the check for deprecated services on the normative references checker:
  https://github.com/plehegar/normative-references/commit/2548dcc69a33ba070638b0f4ffdb4b6afc61f791

The Director will now see those.

**Comment by jennyliang220** [comment]
Shall we add these to 'unreliableDomains' in reliability.js?

https://github.com/w3c/specberus/blob/7c4c048d27ddf4db725bf4e030b080740d51d287/lib/rules/links/reliability.js#L7

This will give a warning.
