### ISSUE TITLE
fixup.js in WDs

### ISSUE THREAD

**Issue by plehegar** [w3c/specberus#816]
The advise:
[[
The document must include the script fixup.js.
]]
https://www.w3.org/pubrules/doc/rules/?profile=CR

Appears on [FPWD](https://www.w3.org/pubrules/doc/rules/?profile=FPWD), [CR](https://www.w3.org/pubrules/doc/rules/?profile=CR), [WG-NOTE](https://www.w3.org/pubrules/doc/rules/?profile=WG-NOTE), etc. profiles but not on [WD](https://www.w3.org/pubrules/doc/rules/?profile=WD). Shouldn't we include fixup.js in WDs as well?

Also, is it really only compounds documents or for single or compounds documents?

**Comment by deniak** [comment]
Right, it's missing from the WD profile documentation.
I'll also move the rule under the section "7. Document Body" as it's mandatory for all types of TR documents.
