### ISSUE TITLE
Bug in rule “headers.copyright”: [link with https for Beihang]

### ISSUE THREAD

**Issue by siusin** [w3c/specberus#817]
The url of Beihang should be allowed with https.

[EXPLANATION]

Found [while checking `https://www.w3.org/TR/2019/WD-user-timing-3-20190305/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2019%2FWD-user-timing-3-20190305%2F&profile=FPWD&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004).

**Comment by deniak** [comment]
This is already fixed by https://github.com/w3c/specberus/pull/805 but not deployed yet. We are scheduling a new release for tomorrow so until then, please ignore the error
