### ISSUE TITLE
Bug in rules: back-to-top 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/specberus#830]
[EXPLANATION]

Found [while checking `http://marcoscaceres.github.io/playground/pr_cr.html`](https://www.w3.org/pubrules/?url=http%3A%2F%2Fmarcoscaceres.github.io%2Fplayground%2Fpr_cr.html%3F&profile=CR&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004).

The p#back-to-top is at the end of the document, but PubRules is not picking it up.

**Comment by jennyliang220** [comment]
`<a href="#toc">`for back-to-top is not right:
- `#toc` is **table of contensts**, which is a fixed sidebar.
- The right anchor for back-to-top anchor should be `<a href="#title">`, the main title at top. 

After changing the anchor to `#title`, http://marcoscaceres.github.io/playground/pr_cr.html should pass the back-top-top test.
