### ISSUE TITLE
Note and Patent Policy wording

### ISSUE THREAD

**Issue by plehegar** [w3c/specberus#849]
specberus expects:

`<p data-deliverer="@@wgId@@">This document was produced by a group
operating under the <a href="https://www.w3.org/Consortium/Patent-Policy/"><abbr title="World Wide Web Consortium">W3C</abbr> Patent
Policy&lt;/a>.</p>`

but [respec](https://github.com/w3c/respec/blob/develop/src/w3c/templates/sotd.js#L222) adds in the same paragraph:

`The group does not expect this document to become a W3C Recommendation.`

not sure how to modify https://github.com/w3c/specberus/blob/master/lib/rules/sotd/pp.js#L25 but it would be nice to relax it.

**Comment by jennyliang220** [comment]
for Working Group Note like [this doc](https://www.w3.org/TR/2019/NOTE-trace-context-protocols-registry-20191119/) wanted changes to be: 

`
This document was produced by a group operating under the( 5 February 2004)? W3C Patent Policy\. ?(The group does not expect this document to become a W3C Recommendation\. )?
`

for Working Dragt like [webrtc-svc](https://www.w3.org/TR/2020/WD-webrtc-svc-20200408/), wanted remains the same: 

`This document was produced by a group operating under the( 5 February 2004)? W3C Patent Policy\. ?W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent\. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim\(s\) must disclose the information in accordance with section 6 of the W3C Patent Policy\.`
