### ISSUE TITLE
back-to-top rule suggests to point to #toc

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#854]
[`back-to-top.js`](https://github.com/w3c/specberus/blob/master/lib/rules/style/back-to-top.js) suggests to add
```
<p role="navigation" id="back-to-top"><a href="#toc"><abbr title="Back to top">&uarr;</abbr></a></p>
```

but with the TOC being available in the sidebar, it doesn't seem to be very useful.
It's probably better to point to the  SotD section.

/cc @ericprud

**Comment by jennyliang220** [comment]
`<a href="#toc">`for back-to-top is not right, `#toc` is **table of contensts**, which is a fixed sidebar, . The right anchor for back-to-top anchor should be `<a href="#title">`, the main title at top.

**Comment by jennyliang220** [comment]
Same question #830, will fix together
