### ISSUE TITLE
Ensure that a WG is publishing documents with the correct W3C Patent Policy version as set in its current charter

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#860]
_[issue title and description was updated based on @plehegar previous clarification]_

<strike>A WG is chartered under a single process document. If we can get that information from the W3C API, we should check if the process document mentioned in the spec matches the one associated with the charter.</strike>

A WG is chartered under a given W3C Patent Policy. If we can get that information from the W3C API, we should check if the Patent Policy mentioned in the spec matches the one from the group charter.

**Comment by vivienlacourba** [comment]
cc: @plehegar

**Comment by vivienlacourba** [comment]
@plehegar told me yesterday that we might actually need to store the patent policy associated to a given group and not its process document (as the current thinking is that all groups would transition to the Process 2020 at once, but that will not be the case for the Patent Policy 2020).
