### ISSUE TITLE
Make sure a WG is using the right document license

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#861]
Check the copyright against the document license associated with a charter.

**Comment by vivienlacourba** [comment]
cc: @plehegar

**Comment by deniak** [comment]
Options can be:
* document license
* software license
* one of the 2 above

**Comment by deniak** [comment]
replaced by the patent policy check

**Comment by jennyliang220** [comment]
This issue duplicates #1166, resolved by PR #1330
