### ISSUE TITLE
Check previous version for Notes unless they are First Public WG Note

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#873]
At the moment, we don't expect Notes to have a previous version. However, this may happen and if it was previously published, we need to make sure the previous version is specified and is the right one.

**Comment by jennyliang220** [comment]
First Public xx Note: no Previous Version in `<dl>`, and no api.w3.org/specifications/<shortname> exist.
Special situation: Short Name Change: https://www.w3.org/TR/2020/WD-webrtc-priority-20200123/
