### ISSUE TITLE
More accurate way to run tests

### ISSUE THREAD

**Issue by jennyliang220** [w3c/specberus#885]
Then specberus run tests, it run through test documents to see if the outcome matches the errors and warnings [identified in the test](https://github.com/w3c/specberus/blob/2ab984ac855af575c1fb139dd630401d4cadcd64/test/rules.js#L305).

But the errors can be defined more precisely, to match the errors and warnings in [l10n-en_GB.js](https://github.com/w3c/specberus/blob/2ab984ac855af575c1fb139dd630401d4cadcd64/lib/l10n-en_GB.js#L117).

## Example
The four `sotd.pp` error can be more accurate if we `sotd.pp -> sotd.pp.no-pp`: 

https://github.com/w3c/specberus/blob/2ab984ac855af575c1fb139dd630401d4cadcd64/test/rules.js#L304-L307

https://github.com/w3c/specberus/blob/2ab984ac855af575c1fb139dd630401d4cadcd64/lib/l10n-en_GB.js#L117-L128

## How to Fix
Ideally, the more strict rules should pass:
```
{
    doc: "online/IG-NOTE-media-timed-events.html",
    errors: ["sotd.charter-disclosure.wrong-link"] // before is ["sotd.charter-disclosure"]
}
```
but the errors are like in the screenshot:
![image](https://user-images.githubusercontent.com/8498677/80163574-257d0780-8609-11ea-9f8e-973900f2b1e8.png)

For errors, change here:
https://github.com/w3c/specberus/blob/2ab984ac855af575c1fb139dd630401d4cadcd64/test/rules.js#L448-L451

For warnings, change here:
https://github.com/w3c/specberus/blob/2ab984ac855af575c1fb139dd630401d4cadcd64/test/rules.js#L454-L459

At first glance, I tried with changing the `contain` inside-out: 
https://github.com/w3c/specberus/blob/2ab984ac855af575c1fb139dd630401d4cadcd64/test/rules.js#L450
```
// before
expect(handler.errors).to.contain(test.errors[i]);

// after (not good)
expect(test.errors[i]).to.contain(handler.errors);
```
but other test failed because the usage of `expect.to.contain` and `handler.errors` is an array.

So we need to look deeper into the test.

**Comment by deniak** [comment]
https://github.com/w3c/specberus/pull/893 is adding the key to the `errrors`, `warnings` and `info` so it should be easy to check the expected errors more accurately.
