### ISSUE TITLE
Working Drafts do not necessarily represent a consensus of the Working Group

### ISSUE THREAD

**Issue by plehegar** [w3c/specberus#902]
Process says:
[[
Working Drafts do not necessarily represent a consensus of the Working Group, and do not imply any endorsement by W3C or its members beyond agreement to work on a general area of technology.
]]

Our boilerplate says:
[[
<p>Publication as a Working Draft does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.</p>
]]

It doesn't make it clear that the document may not represent the consensus for the Working Group.

Should we update the paragraph like:
[[
<p>Publication as a Working Draft does not represent a consensus of the Working Group and does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.</p>
]]

Applicable to FPWD, and WD profiles.

cc @jbrewer @michael-n-cooper

**Comment by michael-n-cooper** [comment]
I don't object to the boilerplate change, given it reflects a statement in the Process doc. The Process wording surprised me and my groups would react to it in different ways, but it's fine for it to be in boilerplate.

**Comment by brewerj** [comment]
@plehegar this better aligns with the Process document, and is important to cite in the status section of drafts, in order to avoid misunderstandings or misrepresentations of the document status.

**Comment by deniak** [comment]
@plehegar since there's an agreement on the suggestion you made, what's the next step ? Contact the generators' maintainers and schedule a deployment date?

**Comment by brewerj** [comment]
@plhegar looking at this once more, I think that the updated wording is missing a word; it needs "necessarily", e.g., does not necessarily represent a consensus of the WG..."

**Comment by plehegar** [comment]
How about:
[[

Publication as a Working Draft does not necessarily represent a consensus of the Working Group and does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

]]

**Comment by plehegar** [comment]
@deniak , let's get the challenges document published (at some point) and separate its publication from this issue. To change specberus, I'd like to circulate the proposal to spec-prod for a week before we move ahead.

**Comment by deniak** [comment]
@plehegar I don't think we want that but we could also allow both wordings until there's a general approval for the new one.

**Comment by plehegar** [comment]
@deniak actually, I like the idea a lot. I does make the documentation longer but at least, it doesn't require making the UI more complex. The Process CG is discussing boilerplate for Process 2020 at the moment btw.

**Comment by brewerj** [comment]
@deniak @plehegar @michael-n-cooper  I support and encourage allowing this language for now, especially given that it aligns more directly with W3C Process than the current boilerplate wording, so it would be good to be able to use this without going through extra hoops. 
Separately, I support PLH's interest in discussing with spec-prod for further feedback as needed. but not as a bar to allowing this wording as an alternative for now, if you have a way to do that Denis.

**Comment by deniak** [comment]
I'll see if @jennyliang220 can fix that issue by tomorrow.

**Comment by deniak** [comment]
@jennyliang220 fixed the issue. The change is now deployed. @michael-n-cooper feel free to submit the document with the new version of the paragraph to Echidna and it should pass.

**Comment by michael-n-cooper** [comment]
Thank you for this change. I confirm it works in a dry-run test: https://labs.w3.org/echidna/api/status?id=d9aa4d2f-c625-4ae7-ac83-be773dc18d22. I will publish via Echidna when the bureaucracy permits.
