### ISSUE TITLE
[process2020] Handle the different types of RECs

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#935]
metadata should differentiate the different types of RECs:
* regular REC
* edited REC with substantive changes
* edited REC with new features

Add 2 new metadata properties for REC only:
* substantive-changes
* new-features

Changes to be implemented:
* All the paragraphs in the SotD are required
* Some RECs now require a comment date ([at least 60 days after the publication](https://www.w3.org/2020/Process-20200915/#change-review))

Mockups:
* https://w3c.github.io/tr-design/p2020mockup/rec-6.2.10.html
* https://w3c.github.io/tr-design/p2020mockup/rec-6.2.11.3.html (substantive corrections)
* https://w3c.github.io/tr-design/p2020mockup/rec-6.2.11.4.html (new features)
* https://w3c.github.io/tr-design/p2020mockup/rec-6.2.11.34.html (substantive corrections *and* new features)

**Comment by jennyliang220** [comment]
Templates: https://github.com/w3c/tr-design/tree/gh-pages/p2020mockup `Recommendation (new features) 6.2.11.4`

**Comment by jennyliang220** [comment]
Add 2 new metadata properties for REC only:

substantive-changes -> substantiveChanges
new-features -> newFeatures

Use camel cases, like 'latestVersion' in metadata
