### ISSUE TITLE
Bug in rule “validation.css”: [WHAT]

### ISSUE THREAD

**Issue by svgeesus** [w3c/specberus#965]
The validator is complaining about lots of supposed errors in the W3C stylesheets!

Found [while checking `https://w3c.github.io/PFE-analysis/report/evaluation-report.html`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fw3c.github.io%2FPFE-analysis%2Freport%2Fevaluation-report.html&profile=FPWG-NOTE&validation=simple-validation&noRecTrack=true&informativeOnly=true&echidnaReady=false&patentPolicy=pp2004).

**Comment by deniak** [comment]
The recent changes (CSS variables) to the TR stylesheets actually don't pass the CSS validator.
I can add a general exception for the parsing error if necessary but this should  probably be fixed in the validator itself
/cc @ylafon @fantasai

**Comment by deniak** [comment]
To avoid future issues like that one, I changed the rule to ignore all the errors for base.css.

/cc @plehegar
