### ISSUE TITLE
Wrong date detection

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#972]
https://github.com/w3c/specberus/blob/main/lib/rules/heuristic/date-format.js reports error when checking documents with references under specific formats.
See https://github.com/w3c/echidna/issues/773

**Comment by jennyliang220** [comment]
Currently date-format.js use an regular expression:

https://github.com/w3c/specberus/blob/921d778cb07bdf068f4a98b0064747731edaedaf/lib/rules/heuristic/date-format.js#L13

In [this document](https://www.w3.org/TR/2020/NOTE-did-spec-registries-20200618/) there is following string:
> HSHQDC-16-R00012-H-SB2016-1-002, 70RSAT20T00000010

when execute, it get `16-1-00` and see it as a possible date. 
> HSHQDC-16-R00012-H-SB20`16-1-00`2, 70RSAT20T00000010

So regular expression need to find possible date with [word boundry](https://www.regular-expressions.info/wordboundaries.html), so 2`\b`s are added to begin and end of RegExp.

**Comment by deniak** [comment]
Proposed solution looks good to me
