### ISSUE TITLE
Rule "The document MUST NOT have any broken internal links or broken links to other resources at w3.org. The document SHOULD NOT have any other broken links.
"

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/specberus#99]
Is it implemented?

**Comment by tripu** [comment]
@dontcallmedom, @astorije: do we consider this solved after #129? ie, is this one really a `display-only` issue?

**Comment by astorije** [comment]
This will need to be thoroughly implemented later. This will result in an error for some documents, like RECs for sure, probably NOTEs in my opinion, and most likely CRs, PRs, PERs, ... I think it should be the case for WDs as well (most if not all of the broken links I spot are thanks to the link checker) but nobody will have time to work on that before v1.
It is unfortunately the kind of things were if not perfectly trustworthy, it will be a pain for editors..

So @tripu, my answer would be: no.

**Comment by tripu** [comment]
Roger that, @astorije.

**Comment by deniak** [comment]
I'll try to add [broken-link-checker](https://github.com/stevenvachon/broken-link-checker) to specberus. Unfortunately that module doesn't detect broken fragments but I submitted https://github.com/stevenvachon/broken-link-checker/pull/22 to start the support.

**Comment by deniak** [comment]
dropped!
